// AUTO-GENERATED by generate-content-data.js — do not edit manually
const BLOG_POSTS = [
  {
    "slug": "/blog/agent-evaluation",
    "title": "Agent Evaluation Metrics: How to Measure AI Agent Performance",
    "description": "How to evaluate AI agents — task completion rate, tool call accuracy, planning quality, cost per task. LangSmith tracing and custom evaluation harness with Python code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/agent-framework-comparison",
    "title": "CrewAI vs LangGraph vs AutoGPT: Agent Framework Comparison",
    "description": "Compare CrewAI, LangGraph, AutoGen, and AutoGPT on ease of use, control, multi-agent support, and production readiness. Includes decision table and code snippets.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "/blog/agent-memory",
    "title": "Memory Systems in AI Agents",
    "description": "Short-term, long-term, episodic, and semantic memory in AI agents. LangChain memory implementations and trade-offs between memory types for production systems.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/agent-planning",
    "title": "Planning Algorithms in AI Agents",
    "description": "How AI agents plan multi-step tasks — ReAct, chain-of-thought, tree of thoughts, and plan-and-execute patterns with working Python code examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/agent-tools",
    "title": "Tool Use in AI Agents",
    "description": "How AI agents select and call tools — tool definitions, function calling, tool chaining. Build custom LangChain tools with web search, code execution, and file I/O.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "/blog/ai-agent-architecture",
    "title": "AI Agent Architecture Explained",
    "description": "Deep dive into AI agent components — perception, LLM reasoning core, memory, tool registry, and execution engine. Compare stateless vs stateful agents.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "/blog/ai-agents-guide",
    "title": "AI Agents Guide: Architecture and Design Patterns",
    "description": "Complete guide to AI agent architecture — perception, planning, memory, tool use, and execution loops for senior engineers building production systems.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "/blog/ai-agents-tutorial",
    "title": "AI Agents Tutorial: Build Autonomous AI Systems (2026)",
    "description": "Step-by-step tutorial for building a working AI agent with Python and LangChain. Build a research agent with full ReAct loop in runnable code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "ann-algorithms",
    "title": "Approximate Nearest Neighbor Algorithms Explained",
    "description": "How ANN algorithms work — HNSW, IVF, ScaNN, and PQ explained with code, benchmarks, and tradeoffs for building fast vector search at scale.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/anthropic-api-tutorial",
    "title": "Anthropic Claude API Tutorial for Python Developers",
    "description": "Complete Anthropic Claude API tutorial — setup, Messages API, streaming, tool use, vision, and system prompts with runnable Python examples for 2026.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/api-vs-local-llm",
    "title": "API vs Local LLM: Which Should You Use?",
    "description": "API vs local LLM comparison — real cost calculations, latency, privacy, and capability trade-offs. Decision framework for choosing between OpenAI API, Ollama, and self-hosted models.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/autonomous-agents",
    "title": "Autonomous Task Execution in AI Agents",
    "description": "How fully autonomous AI agents handle multi-step tasks without human input. Loop architecture, error recovery, self-correction, and production safety considerations.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "chain-of-thought-prompting",
    "title": "Chain-of-Thought Prompting Explained for Developers",
    "description": "A developer's guide to chain-of-thought prompting — how it works, when to use it, and production implementations including zero-shot CoT, self-consistency, and Tree of Thought.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "context-window-rag",
    "title": "Context Window Optimization in RAG Systems",
    "description": "Learn how to optimize context window usage in RAG systems. Covers chunk selection, context compression, reranking, and prompt design to maximize LLM answer quality.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/distributed-llm-training",
    "title": "Distributed Training for LLMs: Scale Beyond One GPU",
    "description": "Data parallelism, model parallelism, tensor and pipeline parallelism for LLMs. DeepSpeed ZeRO stages, FSDP with HuggingFace Accelerate, and config examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "embedding-model-comparison",
    "title": "Embedding Model Comparison for Vector Search",
    "description": "Compare OpenAI, BGE, E5, Cohere, and Voyage embedding models for vector search — benchmarks, pricing, dimensions, and which to use for production RAG.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "embeddings-explained",
    "title": "Embeddings Explained: How AI Understands Text",
    "description": "Deep dive into AI embeddings — how models convert text to vectors, which models to choose, how similarity works, and how to use embeddings in production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "few-shot-vs-zero-shot",
    "title": "Few-Shot vs Zero-Shot Prompting Explained",
    "description": "Understand the practical differences between few-shot and zero-shot prompting — when to use each, how to write examples, and the cost vs. accuracy trade-offs.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/fine-tune-open-source-llm",
    "title": "Fine-Tuning Open Source LLMs: From Llama to Production",
    "description": "End-to-end guide to fine-tuning Llama 3 with Unsloth and TRL — dataset prep, LoRA training, merging adapters, exporting to GGUF, and serving with Ollama.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "/blog/finetuning-datasets",
    "title": "Dataset Preparation for LLM Fine-Tuning",
    "description": "How to prepare high-quality datasets for LLM fine-tuning: Alpaca format, ShareGPT, deduplication, quality filtering, synthetic data with GPT-4, and HuggingFace datasets.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/full-vs-lora",
    "title": "Full Fine-Tuning vs LoRA: When to Use Each",
    "description": "Head-to-head comparison of full fine-tuning vs LoRA for LLMs. Compute cost, memory, quality, and speed with real numbers to guide your decision.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/gemini-api-tutorial",
    "title": "Google Gemini API Tutorial for Developers",
    "description": "Complete Google Gemini API tutorial — setup, generateContent, streaming, multimodal inputs, function calling, and safety settings with Python SDK examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "/blog/gguf-models",
    "title": "GGUF Models Explained: The Format Powering Local LLMs",
    "description": "Understand GGUF — what it is, how llama.cpp uses it, Q4_K_M vs Q5_K_M vs Q8_0 quant levels, finding models on HuggingFace, and loading with llama-cpp-python.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/huggingface-training",
    "title": "Training LLMs with HuggingFace: Complete Guide",
    "description": "Complete guide to HuggingFace LLM training: Trainer, TRL SFTTrainer, DPOTrainer, Accelerate for multi-GPU, and PEFT for parameter-efficient fine-tuning.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "hybrid-search-rag",
    "title": "Hybrid Search in RAG Systems",
    "description": "Learn how hybrid search combines vector and keyword search in RAG systems to improve retrieval precision for technical and domain-specific content.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/instruction-tuning",
    "title": "Instruction Tuning Explained: How LLMs Learn to Follow Instructions",
    "description": "Instruction tuning teaches LLMs to follow natural language instructions via supervised fine-tuning. Covers Alpaca format, chat templates, multi-turn data, and TRL SFTTrainer.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/langchain-agents",
    "title": "Building Agents with LangChain: Complete Tutorial",
    "description": "Build a LangChain agent from scratch — AgentExecutor, tools, ReAct prompting. Working code for a research agent with DuckDuckGo, Wikipedia, and Python REPL.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/llm-api-cost-optimization",
    "title": "LLM API Cost Optimization: Reduce Costs by 60%+",
    "description": "Cut LLM API costs by 60% or more with prompt caching, model routing, response caching, prompt compression, and batch API. Real cost math included.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 12
  },
  {
    "slug": "/blog/llm-api-errors",
    "title": "LLM API Error Handling Best Practices",
    "description": "Handle LLM API errors in production — 429 rate limits, 500 server errors, context length exceeded, content filters, circuit breaker pattern, and fallback providers.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 12
  },
  {
    "slug": "/blog/llm-api-guide",
    "title": "LLM APIs Guide for Developers",
    "description": "Complete guide to working with LLM APIs — authentication, tokens, streaming, function calling, error handling, and cost management across OpenAI, Anthropic, and Gemini.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "/blog/llm-benchmarks",
    "title": "LLM Benchmarks Explained: How to Compare AI Models",
    "description": "Understand key LLM benchmarks — MMLU, HumanEval, MATH, MT-Bench, GPQA, IFEval — what they measure, benchmark gaming, and how to run your own evals with lm-eval-harness.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/llm-evaluation",
    "title": "Evaluation Metrics for LLMs: How to Measure Quality",
    "description": "How to evaluate LLM quality with BLEU, ROUGE, perplexity, LLM-as-judge, lm-eval-harness, and custom task-specific evals. With code for running evaluations.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/llm-fine-tuning-guide",
    "title": "LLM Fine-Tuning Guide: LoRA, QLoRA, and Full Fine-Tuning",
    "description": "Complete guide to LLM fine-tuning: when to use LoRA vs QLoRA vs full fine-tuning, dataset prep, training infra, and evaluation with TRL and Unsloth.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/llm-function-calling",
    "title": "Function Calling with LLM APIs: Practical Guide",
    "description": "Master LLM function calling — OpenAI tool schemas, parallel tool calls, tool choice, chaining tool results, and building real weather and calculator tool examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "/blog/llm-hardware-guide",
    "title": "GPU Requirements for Running LLMs Locally",
    "description": "Practical GPU and hardware guide for running LLMs locally — VRAM requirements by model size, GPU comparisons, Apple Silicon performance, and CPU-only inference options.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 12
  },
  {
    "slug": "/blog/llm-quantization",
    "title": "LLM Quantization Explained: Run Bigger Models on Less Hardware",
    "description": "Understand LLM quantization — INT8, INT4, GGUF formats, quality vs size trade-offs, BitsAndBytes, and how to choose the right quantization level for production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/llm-rate-limits",
    "title": "Rate Limiting Strategies for LLM APIs",
    "description": "Handle LLM API rate limits in production — TPM/RPM limits by tier, exponential backoff with jitter, token bucket implementation, queue-based throttling, and Azure PTU vs PAYG.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/llm-streaming",
    "title": "Streaming Responses from LLM APIs: Complete Guide",
    "description": "Learn how LLM API streaming works with SSE, implement streaming in OpenAI, Anthropic, and Gemini, and build a streaming FastAPI backend with real Python code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/local-ai-development",
    "title": "Local AI Development Setup: Run LLMs Without the Cloud",
    "description": "Complete local AI development environment — Ollama, Python, LangChain with local models, ChromaDB for local RAG, and a fully local RAG chatbot from scratch.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "/blog/lora-fine-tuning-tutorial",
    "title": "LoRA Fine-Tuning Tutorial for LLMs (2026 Guide)",
    "description": "Step-by-step LoRA fine-tuning tutorial for Llama 3 using Unsloth, TRL, and PEFT. Covers dataset formatting, training config, adapter merging, and testing.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/model-distillation",
    "title": "Model Distillation Explained: Smaller Models, Similar Performance",
    "description": "Understand knowledge distillation for LLMs — teacher-student training, response distillation, distillation vs quantization, and Python examples with Hugging Face Transformers.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/multi-agent-systems",
    "title": "Multi-Agent Systems Explained",
    "description": "Multi-agent coordination patterns — supervisor-worker, peer-to-peer, hierarchical. When to use multi-agent vs single agent, with CrewAI and LangGraph examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "multi-document-rag",
    "title": "Multi-Document Retrieval in RAG Pipelines",
    "description": "Learn how to build multi-document RAG pipelines that retrieve and synthesize information across multiple sources, with routing, filtering, and fusion strategies.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "/blog/ollama-tutorial",
    "title": "Running LLMs Locally with Ollama: Complete Guide",
    "description": "Complete Ollama tutorial — install, pull models, Python integration, custom Modelfiles, GPU vs CPU inference, and building a local chatbot with streaming.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/open-source-llm-comparison",
    "title": "Best Open Source LLMs Compared: Llama vs Mistral vs Qwen (2026)",
    "description": "Compare Llama 3.3 70B, Mistral 7B/24B, Qwen 2.5, Phi-4, and Gemma 3 on benchmarks, hardware needs, and practical use cases for production AI systems.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "/blog/open-source-llm-guide",
    "title": "Open Source LLMs Guide: Llama, Mistral, Qwen and Beyond",
    "description": "Complete guide to the open source LLM ecosystem — model families, local runtimes, quantization formats, hardware requirements, and when to use open vs closed models.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 13
  },
  {
    "slug": "/blog/open-vs-closed-llm",
    "title": "Open Source vs Proprietary LLMs: Which to Choose?",
    "description": "Practical decision framework for open vs closed LLMs — capability, cost, privacy, fine-tuning control, vendor lock-in, and when each makes sense for production systems.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "/blog/openai-api-tutorial",
    "title": "OpenAI API Tutorial for Developers (2026)",
    "description": "Complete OpenAI API tutorial — setup, chat completions, streaming, function calling, embeddings, vision, token counting, error handling, and retry logic for 2026.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 14
  },
  {
    "slug": "/blog/openai-langchain",
    "title": "Building AI Apps with OpenAI and LangChain",
    "description": "Build AI applications with OpenAI and LangChain — ChatOpenAI, LCEL chains, memory, tools, and a complete document Q&A app. Honest comparison of raw API vs LangChain.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "production-rag",
    "title": "Production RAG System Design",
    "description": "Design and deploy production RAG systems that handle real traffic. Covers architecture, caching, monitoring, scaling, and reliability patterns for RAG in production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-best-practices",
    "title": "Prompt Engineering Best Practices for Large Language Models",
    "description": "Production-tested prompt engineering best practices for LLMs — covering reliability, cost, structured output, evaluation, and prompt lifecycle management.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-examples",
    "title": "Prompt Engineering Examples for Real AI Applications",
    "description": "Practical prompt engineering examples for production AI use cases — classification, extraction, summarization, code review, RAG, and agent workflows.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-guide",
    "title": "Prompt Engineering Guide for AI Developers",
    "description": "A practical prompt engineering guide for developers. Learn techniques, patterns, and production best practices for working with modern LLMs in 2026.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-mistakes",
    "title": "Common Prompt Engineering Mistakes Developers Make",
    "description": "The most common prompt engineering mistakes developers make in production — and how to fix them with concrete, actionable techniques.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-techniques",
    "title": "26 Prompt Engineering Techniques Every AI Developer Should Know (2026 Guide)",
    "description": "A complete reference of 26 prompt engineering techniques used in production AI systems — from zero-shot basics to agent loops and self-critique patterns.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "prompt-injection",
    "title": "Prompt Injection Attacks and How to Prevent Them",
    "description": "Understand prompt injection attacks — how they work, real-world examples, and practical defenses for production LLM applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-templates",
    "title": "Prompt Templates for AI Applications",
    "description": "Learn how to build reusable, maintainable prompt templates for production AI applications — covering parameterization, versioning, and testing patterns.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 7
  },
  {
    "slug": "/blog/qlora-explained",
    "title": "QLoRA Explained: Efficient LLM Fine-Tuning on Consumer Hardware",
    "description": "QLoRA combines 4-bit NF4 quantization with LoRA adapters to fine-tune 13B+ LLMs on a single GPU. Complete guide with BitsAndBytes, PEFT, and TRL code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "rag-architecture-guide",
    "title": "RAG Architecture Guide for AI Developers",
    "description": "A complete guide to retrieval augmented generation architecture — how RAG systems work, when to use them, and how to build them for production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "rag-chatbot",
    "title": "Build a RAG Chatbot with Python and Vector Databases",
    "description": "Build a RAG chatbot with Python, LangChain, and ChromaDB. Add conversation memory, source citations, and streaming — with production-ready code examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "rag-chunking-strategies",
    "title": "Chunking Strategies for RAG Pipelines",
    "description": "Learn the best chunking strategies for RAG pipelines. Compare fixed-size, semantic, and recursive chunking with Python code examples and practical tuning guidance.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "rag-evaluation",
    "title": "RAG Evaluation Metrics Explained",
    "description": "Learn how to evaluate RAG systems using faithfulness, answer relevancy, context precision, and recall metrics. Includes RAGAS implementation and LLM-as-judge patterns.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "rag-tutorial",
    "title": "RAG Tutorial: Build Retrieval-Augmented Generation Systems (2026)",
    "description": "Step-by-step RAG tutorial for developers. Build a complete retrieval-augmented generation system using LangChain, OpenAI, and ChromaDB with runnable Python code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "rag-vs-finetuning",
    "title": "RAG vs Fine-Tuning: When to Use Each",
    "description": "Understand when to use RAG vs fine-tuning for LLM applications. Compare cost, latency, accuracy, and maintenance for each approach with real engineering examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "/blog/rlhf-guide",
    "title": "RLHF Explained: How LLMs Learn from Human Feedback",
    "description": "RLHF pipeline explained: SFT to reward model to PPO. DPO as a simpler alternative. TRL DPOTrainer code. Practical challenges of reward hacking and training instability.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "role-prompting",
    "title": "Role Prompting Explained for LLMs",
    "description": "Learn how role prompting shapes LLM outputs — when persona assignment improves results, how to write effective role prompts, and the trade-offs to know.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "semantic-search-vector",
    "title": "Semantic Search with Vector Databases",
    "description": "Build production semantic search with vector databases — hybrid BM25 + vector search, re-ranking, metadata filtering, and real Python examples with ChromaDB.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "/blog/synthetic-data-llm",
    "title": "Synthetic Data for LLM Training: Generate Your Own Dataset",
    "description": "How to generate synthetic training data for LLM fine-tuning using GPT-4 and Claude. Self-instruct method, Evol-Instruct, quality filtering, and a complete 1,000-example generation script.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "system-prompts-guide",
    "title": "System Prompts: How to Control LLM Behavior",
    "description": "Learn how to write effective system prompts that control LLM tone, persona, output format, and safety constraints across production AI applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "vector-database-comparison",
    "title": "Vector Databases Explained: Chroma vs Pinecone vs FAISS (2026)",
    "description": "Hands-on comparison of Chroma, Pinecone, FAISS, Weaviate, and pgvector — performance, pricing, and when to choose each for AI applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 7
  },
  {
    "slug": "vector-database-guide",
    "title": "Vector Databases Guide for AI Applications",
    "description": "Complete guide to vector databases for AI apps — embeddings, similarity search, HNSW indexing, and how to pick the right vector DB for production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-database-scaling",
    "title": "Scaling Vector Databases in Production",
    "description": "How to scale vector databases for production — sharding, replication, query optimization, caching, and architecture patterns for high-throughput AI apps.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-indexing",
    "title": "Vector Indexing Techniques Explained",
    "description": "Vector indexing from flat to HNSW, IVF, and PQ — how each technique works, when to use it, and Python examples with FAISS and ChromaDB.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-recommendation-systems",
    "title": "Building Recommendation Systems with Vector Search",
    "description": "Build production recommendation systems using vector search — item embeddings, collaborative filtering with vectors, two-tower models, and real Python examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "vector-search-explained",
    "title": "Vector Search Explained for AI Developers",
    "description": "How vector search works under the hood — embeddings, distance metrics, ANN algorithms, and building a production semantic search system step by step.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-vs-keyword-search",
    "title": "Vector Search vs Keyword Search in RAG",
    "description": "Compare vector search vs keyword search for RAG systems. Understand when semantic search beats BM25, when it fails, and how to choose the right retrieval strategy.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-vs-relational-db",
    "title": "Vector Database vs Traditional Database",
    "description": "Vector database vs relational database — when to use each, how they differ architecturally, and practical guidance on hybrid approaches for AI applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "advanced-prompt-engineering",
    "title": "Advanced Prompt Engineering Techniques for LLMs",
    "description": "Learn advanced prompt engineering strategies including prompt chaining and tool use.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 8
  },
  {
    "slug": "ai-learning-roadmap",
    "title": "AI Learning Roadmap for Developers (2026)",
    "description": "A step-by-step roadmap for developers to learn AI and build AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 8
  },
  {
    "slug": "ai-tools-for-developers",
    "title": "Best AI Tools for Developers in 2026",
    "description": "Explore the best AI tools developers use to build modern AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "attention-mechanism-explained",
    "title": "Attention Mechanism Explained in Simple Terms",
    "description": "Understand how attention mechanisms allow AI models to focus on relevant context.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-ai-agents",
    "title": "How to Build AI Agents Step-by-Step",
    "description": "Learn how developers build AI agents using LLM frameworks.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "build-ai-app",
    "title": "How to Build Your First AI Application",
    "description": "A practical guide for developers building AI-powered applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-rag-app",
    "title": "How to Build a RAG Application Step-by-Step",
    "description": "Learn how to build a Retrieval-Augmented Generation app using vector databases and LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "few-shot-prompting-explained",
    "title": "Few-Shot Prompting Explained – Improve LLM Output",
    "description": "Understand how few-shot prompting works and how developers guide LLM responses.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "how-llms-work",
    "title": "How Large Language Models Work (Simple Guide)",
    "description": "Understand how large language models work including transformers and tokens.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "langchain-tutorial",
    "title": "LangChain Tutorial – Build AI Applications with LLMs",
    "description": "Learn how to use LangChain to build AI applications with LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "lora-fine-tuning-explained",
    "title": "LoRA Fine-Tuning Explained – Efficient LLM Training",
    "description": "Learn how LoRA fine-tuning works and why it is efficient.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "openai-python-client-guide",
    "title": "OpenAI Python Client Guide – Chat, Embeddings, Tools",
    "description": "Learn how to use the OpenAI Python client to build AI apps.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "rag-explained",
    "title": "RAG Explained – How Retrieval-Augmented Generation Works",
    "description": "Learn how Retrieval-Augmented Generation works and how developers build RAG systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "run-llms-locally",
    "title": "How to Run LLMs Locally Using Ollama",
    "description": "Learn how to run large language models locally using Ollama.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "transformer-architecture-explained",
    "title": "Transformer Architecture Explained for Developers",
    "description": "Learn how transformer models power modern AI systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "vector-database-explained",
    "title": "Vector Databases Explained – FAISS, Pinecone, Weaviate",
    "description": "Learn how vector databases power semantic search and AI retrieval systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "ai-agent-fundamentals",
    "title": "AI Agent Fundamentals: How LLM Agents Think, Plan, and Act",
    "description": "Learn the building blocks of AI agents — ReAct loops, tool use, planning, memory, and multi-agent coordination. Includes hands-on examples with LangChain and OpenAI.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "ai-application-architecture",
    "title": "AI Application Architecture: Designing Production-Ready LLM Systems",
    "description": "Architectural patterns for production AI applications — prompt management, context windows, fallback strategies, observability, cost control, and testing LLM systems.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 6
  },
  {
    "slug": "building-ai-chatbots",
    "title": "Building AI Chatbots: From Simple Q&A to Contextual Conversations",
    "description": "Step-by-step guide to building AI chatbots — multi-turn conversations, conversation memory, RAG-powered bots, streaming responses, and deploying a chat UI.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "deploying-ai-applications",
    "title": "Deploying AI Applications: From Local Dev to Production",
    "description": "Step-by-step guide to deploying AI applications — FastAPI serving, Docker containers, cloud deployment on AWS/GCP, model caching, rate limiting, and monitoring.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "document-chunking-strategies",
    "title": "Document Chunking Strategies for RAG: How to Split Text for Better Retrieval",
    "description": "Learn the best document chunking strategies for RAG — fixed size, sentence, semantic, and hierarchical chunking. Includes benchmarks and code for each approach.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "feature-engineering-guide",
    "title": "Feature Engineering Guide: Transform Raw Data into Model-Ready Features",
    "description": "Practical feature engineering techniques for ML engineers — encoding, scaling, handling missing values, creating new features, and selecting the most useful ones.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "fine-tuning-llms-guide",
    "title": "Fine-Tuning LLMs: Complete Guide to Instruction Tuning and LoRA",
    "description": "Learn how to fine-tune large language models — full fine-tuning vs LoRA vs QLoRA, dataset preparation, training with Hugging Face, and avoiding common pitfalls.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "langchain-rag-tutorial",
    "title": "LangChain RAG Tutorial: Build a Document Q&A System Step by Step",
    "description": "Build a complete RAG pipeline with LangChain — document loading, text splitting, vector store indexing, retrieval chains, and conversational Q&A with memory.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "langchain-tutorial-complete",
    "title": "LangChain Complete Tutorial: Chains, Agents, Tools, and Memory",
    "description": "Master LangChain from scratch — LLM wrappers, prompt templates, chains, LCEL, agents with tools, memory, and building production applications.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "llm-inference-and-serving",
    "title": "LLM Inference and Serving: vLLM, Ollama, and Production Optimization",
    "description": "Guide to LLM inference optimization — KV cache, continuous batching, quantization, vLLM serving, Ollama local deployment, and benchmarking throughput and latency.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "machine-learning-basics-for-developers",
    "title": "Machine Learning Basics for Developers: A Practical Introduction",
    "description": "A developer-first introduction to machine learning — core concepts, types of ML, hands-on Python workflow, and how to go from data to a working model.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "model-evaluation-and-metrics",
    "title": "Model Evaluation and Metrics: How to Measure ML Model Performance",
    "description": "Complete guide to ML evaluation metrics — accuracy, precision, recall, F1, AUC-ROC, RMSE, confusion matrices, learning curves, and cross-validation strategies.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "open-source-llms-guide",
    "title": "Open Source LLMs Guide: Llama, Mistral, Gemma, and How to Run Them Locally",
    "description": "Compare the top open source LLMs — Llama 3, Mistral, Gemma, Phi — and learn how to run them locally with Ollama, llama.cpp, and Hugging Face Transformers.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "openai-api-complete-guide",
    "title": "OpenAI API Complete Guide: Chat, Embeddings, Functions, and Streaming",
    "description": "Master the OpenAI API — chat completions, function calling, embeddings, streaming responses, error handling, cost optimization, and building production-ready integrations.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "python-for-machine-learning",
    "title": "Python for Machine Learning: NumPy, Pandas, and Scikit-learn Essentials",
    "description": "The Python toolkit every ML engineer needs — NumPy arrays, pandas DataFrames, data visualization with matplotlib, and scikit-learn's core API.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "rag-system-architecture",
    "title": "RAG System Architecture: Design Patterns for Production Retrieval-Augmented Generation",
    "description": "Architecture guide for production RAG systems — naive RAG vs advanced RAG, indexing pipelines, hybrid search, reranking, guardrails, and performance optimization.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "supervised-learning-guide",
    "title": "Supervised Learning Guide: Algorithms, Workflows, and Best Practices",
    "description": "Deep dive into supervised learning — regression and classification algorithms, evaluation metrics, cross-validation, and how to pick the right model for your problem.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "tool-use-and-function-calling",
    "title": "Tool Use and Function Calling in LLMs: Practical Patterns and Best Practices",
    "description": "Complete guide to LLM function calling — defining tools, parallel tool calls, error handling, designing reliable tool schemas, and building agentic pipelines.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ai-roadmap-for-developers",
    "title": "AI Roadmap for Developers 2026: The Complete Learning Path",
    "description": "The definitive AI learning roadmap for software developers in 2026. Follow 7 phases from AI foundations to building and shipping real AI projects — with free resources and milestone projects.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 7
  },
  {
    "slug": "how-to-become-ai-engineer",
    "title": "How to Become an AI Engineer in 2026 (From Any Background)",
    "description": "A practical guide to becoming an AI engineer in 2026. Learn what skills you need, how long it takes, what to build, and how to land your first AI engineering role — from any starting point.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 5
  },
  {
    "slug": "machine-learning-roadmap",
    "title": "Machine Learning Roadmap 2026: From Beginner to Job-Ready",
    "description": "The complete machine learning roadmap for 2026. Learn Python, math fundamentals, classical ML, deep learning, LLMs, and MLOps — with free resources and project milestones at each stage.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 6
  },
  {
    "slug": "rag-tutorial-step-by-step",
    "title": "RAG Tutorial 2026: Build a Retrieval-Augmented Generation Pipeline from Scratch",
    "description": "Step-by-step RAG tutorial for developers in 2026. Build a complete Retrieval-Augmented Generation pipeline — document loading, chunking, vector embeddings, semantic search, and LLM generation with LangChain and ChromaDB.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 5
  }
];
const ROADMAP_GUIDES = [
  {
    "slug": "ai-agent-evaluation",
    "title": "AI Agent Evaluation: Testing, Benchmarking, and Safety for Agentic Systems",
    "description": "Learn how to rigorously evaluate AI agents — building test suites, measuring task completion rates, detecting failures, red-teaming, and implementing safety guardrails for production deployments.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ai-foundations-for-developers",
    "title": "AI Foundations for Developers: Core Concepts You Must Know",
    "description": "A developer-focused introduction to AI fundamentals: what AI, ML, and deep learning actually are, how they differ, and the mental models you need before writing your first AI application.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "building-ai-agents-guide",
    "title": "Building AI Agents: ReAct, Tool Use, and Agentic Workflows",
    "description": "A practical guide to building AI agents that can reason and act — covering the ReAct pattern, tool definition, agent loops, memory strategies, and multi-step task execution with OpenAI function calling.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "deep-learning-fundamentals",
    "title": "Deep Learning Fundamentals: CNNs, RNNs, and the Road to Transformers",
    "description": "Understand the deep learning architectures that shaped modern AI — convolutional networks for images, recurrent networks for sequences, and how their limitations led to the transformer revolution.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "how-llms-work",
    "title": "How LLMs Work: From Pretraining to ChatGPT — A Developer's Guide",
    "description": "A technical deep dive into how large language models actually work — tokenization, pretraining, RLHF, inference, and the architectural decisions that define modern LLMs like GPT-4 and Claude.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 6
  },
  {
    "slug": "linear-algebra-for-ai",
    "title": "Linear Algebra for AI Developers: The Concepts That Actually Matter",
    "description": "A practical guide to the linear algebra used in AI and machine learning — vectors, matrices, dot products, and matrix multiplication explained with Python code and real AI use cases.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ml-project-workflow",
    "title": "ML Project Workflow: End-to-End Machine Learning in Practice",
    "description": "A practical guide to the full machine learning project lifecycle — problem framing, data collection, feature engineering, model selection, evaluation, and deployment — with Python code at every step.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "neural-networks-from-scratch",
    "title": "Neural Networks from Scratch: Build One in Pure Python",
    "description": "Build a neural network from scratch using only NumPy to understand how forward passes, backpropagation, and gradient descent actually work. No frameworks, just the math made concrete.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "production-rag-best-practices",
    "title": "Production RAG Best Practices: Chunking, Reranking, and Evaluation",
    "description": "Go beyond basic RAG with advanced techniques: recursive chunking strategies, metadata filtering, reranking retrieved documents, evaluating RAG pipelines, and building production-ready retrieval systems.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "python-for-ai-complete-guide",
    "title": "Python for AI Developers: Complete Setup and Essential Libraries",
    "description": "Set up a production-ready Python AI development environment. Covers virtual environments, essential libraries (NumPy, pandas, OpenAI SDK), Jupyter notebooks, and common patterns used in AI projects.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "pytorch-for-ai-developers",
    "title": "PyTorch for AI Developers: Practical Guide from Tensors to Training",
    "description": "A hands-on PyTorch guide covering tensors, autograd, model building with nn.Module, training loops, GPU acceleration, and loading pre-trained models from HuggingFace.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "semantic-search-explained",
    "title": "Semantic Search Explained: How Embeddings Enable Meaning-Based Search",
    "description": "Understand how semantic search works — from text embeddings and vector spaces to HNSW indexes and approximate nearest neighbor search. Build a production-quality semantic search engine in Python.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "statistics-for-machine-learning",
    "title": "Statistics for Machine Learning: Practical Concepts for Developers",
    "description": "The statistical concepts that actually matter for ML practitioners — probability distributions, Bayes' theorem, hypothesis testing, and how to interpret model evaluation metrics correctly.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "working-with-local-llms",
    "title": "Working with Local LLMs: Run AI Models Privately with Ollama and llama.cpp",
    "description": "Run powerful LLMs completely offline on your own hardware. Set up Ollama, run Llama 3, Mistral, and Code Llama locally, build Python integrations, and understand when to use local vs API models.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  }
];
const PROJECT_LIST = [
  {
    "slug": "ai-chatbot-python",
    "title": "Build an AI Chatbot in Python: Complete Beginner Project",
    "description": "Build a multi-turn AI chatbot in Python using the OpenAI API. Includes conversation memory, streaming, a CLI interface, and a simple Gradio web UI.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Gradio"
  },
  {
    "slug": "ai-code-explainer",
    "title": "Build an AI Code Explainer: Understand Any Code Instantly",
    "description": "Build a tool that explains code in plain English, identifies bugs, suggests improvements, and generates documentation — for any programming language.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Click"
  },
  {
    "slug": "ai-email-writer",
    "title": "Build an AI Email Writer: Draft Professional Emails in Seconds",
    "description": "Build an AI tool that drafts professional emails from bullet points or brief descriptions. Supports multiple tones, templates, and a Streamlit web UI.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Streamlit"
  },
  {
    "slug": "ai-quiz-generator",
    "title": "Build an AI Quiz Generator from Any Text or Document",
    "description": "Build an AI tool that generates multiple-choice quizzes from any text, PDF, or topic. Export to JSON, run interactively, and track scores.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, JSON"
  },
  {
    "slug": "ai-resume-analyzer",
    "title": "Build an AI Resume Analyzer: Score, Critique, and Improve Resumes",
    "description": "Build a tool that analyzes resumes against job descriptions, scores fit, identifies gaps, and suggests specific improvements using GPT-4o-mini.",
    "level": "Beginner",
    "time": "3–4 hours",
    "stack": "Python, OpenAI API, pypdf, Streamlit"
  },
  {
    "slug": "build-chatgpt-clone",
    "title": "Build a ChatGPT Clone from Scratch: Full-Stack AI Chat App",
    "description": "Build a full-stack conversational AI app with streaming responses, persistent conversation history, and a React chat UI — using FastAPI and the OpenAI API.",
    "level": "Beginner",
    "time": "3–4 hours",
    "stack": "Python, FastAPI, React, OpenAI API"
  },
  {
    "slug": "document-summarizer",
    "title": "Build an AI Document Summarizer: PDF, Text, and URL Summarization",
    "description": "Build an AI-powered document summarizer that handles PDFs, plain text, and web URLs. Supports map-reduce summarization for long documents and outputs key bullet points.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, PyPDF2, BeautifulSoup"
  },
  {
    "slug": "sentiment-analyzer",
    "title": "Build an AI Sentiment Analyzer: Classify Text Sentiment and Emotions",
    "description": "Build a sentiment analysis tool using GPT-4o-mini that classifies text as positive, negative, or neutral, detects emotions, and processes batches of reviews or tweets.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, pandas"
  },
  {
    "slug": "ai-content-moderator",
    "title": "Build an AI Content Moderator: Classify and Filter Harmful Content",
    "description": "Build a content moderation system that classifies text and images for toxicity, hate speech, spam, and policy violations. Includes a review queue and confidence thresholds.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API (Moderation + GPT), FastAPI, SQLite"
  },
  {
    "slug": "ai-data-analyst",
    "title": "Build an AI Data Analyst: Chat with Your CSV Data",
    "description": "Build a natural language data analysis tool that lets you ask questions about CSV datasets. Generates and executes Python pandas code, produces charts, and explains insights automatically.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API, pandas, matplotlib, Streamlit"
  },
  {
    "slug": "ai-meeting-summarizer",
    "title": "Build an AI Meeting Summarizer: Transcribe and Summarize Meetings Automatically",
    "description": "Build a tool that transcribes audio recordings with Whisper, summarizes with GPT-4o-mini, extracts action items, decisions, and attendee contributions into a structured meeting report.",
    "level": "Intermediate",
    "time": "3–5 hours",
    "stack": "Python, OpenAI API (Whisper + GPT), Streamlit"
  },
  {
    "slug": "ai-research-assistant",
    "title": "Build an AI Research Assistant: Summarize Papers and Extract Insights",
    "description": "Build an AI tool that reads academic papers and web pages, extracts key findings, compares multiple sources, and generates research summaries with citations.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API, requests, BeautifulSoup, Streamlit"
  },
  {
    "slug": "ai-support-bot",
    "title": "Build an AI Customer Support Bot with Knowledge Base",
    "description": "Build a production-ready customer support chatbot that answers questions from your documentation, escalates complex issues, maintains conversation history, and handles tone appropriately.",
    "level": "Intermediate",
    "time": "5–6 hours",
    "stack": "Python, OpenAI API, ChromaDB, FastAPI, Streamlit"
  },
  {
    "slug": "rag-document-assistant",
    "title": "Build a RAG Document Assistant: Chat with Your Documents",
    "description": "Build a Retrieval-Augmented Generation system that lets you upload documents and ask questions. Uses embeddings, vector search, and GPT-4o-mini for accurate, grounded answers.",
    "level": "Intermediate",
    "time": "4–6 hours",
    "stack": "Python, OpenAI API, ChromaDB, Streamlit"
  },
  {
    "slug": "voice-ai-assistant",
    "title": "Build a Voice AI Assistant: Speech-to-Speech Conversational AI",
    "description": "Build a voice-enabled AI assistant using Whisper for speech recognition, GPT-4o-mini for responses, and TTS for natural voice output. Supports wake word detection and conversation memory.",
    "level": "Intermediate",
    "time": "4–6 hours",
    "stack": "Python, OpenAI API (Whisper + GPT + TTS), sounddevice, pygame"
  },
  {
    "slug": "ai-code-review-assistant",
    "title": "Build an AI Code Review Assistant: Automated PR Reviews",
    "description": "Build a tool that reviews Git diffs and pull requests, identifies bugs, security issues, style violations, and suggests improvements — integrated with GitHub Actions.",
    "level": "Advanced",
    "time": "6–8 hours",
    "stack": "Python, OpenAI API, GitHub API, FastAPI"
  },
  {
    "slug": "ai-personal-knowledge-base",
    "title": "Build an AI Personal Knowledge Base: Your Second Brain with AI",
    "description": "Build a personal knowledge management system that ingests notes, web clips, and PDFs, auto-links related content, and lets you have conversations with your accumulated knowledge.",
    "level": "Advanced",
    "time": "8–12 hours",
    "stack": "Python, OpenAI API, ChromaDB, SQLite, Streamlit"
  },
  {
    "slug": "ai-sales-agent",
    "title": "Build an AI Sales Agent: Automated Lead Qualification and Outreach",
    "description": "Build an AI sales agent that qualifies leads from a CRM, personalizes outreach emails based on company research, tracks responses, and generates pipeline reports.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, SQLite, FastAPI, requests"
  },
  {
    "slug": "ai-security-analyzer",
    "title": "Build an AI Security Analyzer: Automated Vulnerability Detection",
    "description": "Build a static analysis tool that scans codebases for security vulnerabilities using GPT-4o-mini, detecting OWASP Top 10 issues, secrets in code, and insecure patterns with severity scoring.",
    "level": "Advanced",
    "time": "6–8 hours",
    "stack": "Python, OpenAI API, GitPython, Click"
  },
  {
    "slug": "ai-study-planner",
    "title": "Build an AI Study Planner: Personalized Learning Schedules with Spaced Repetition",
    "description": "Build an AI study planner that creates personalized schedules, generates practice questions using spaced repetition, tracks progress, and adapts the plan based on performance.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, SQLite, Streamlit, schedule"
  },
  {
    "slug": "multi-agent-research-system",
    "title": "Build a Multi-Agent Research System: Parallel AI Agents for Deep Research",
    "description": "Build a multi-agent system where a Planner agent breaks research questions into sub-tasks, Researcher agents gather information in parallel, and a Synthesizer agent produces a comprehensive report.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, asyncio, Tavily Search API, Streamlit"
  }
];
const PATH_LIST = [
  {
    "slug": "ai-engineer",
    "title": "AI Engineer Learning Path",
    "description": "A complete roadmap to becoming an AI Engineer — the generalist role that designs, builds, and ships AI-powered applications and systems in production.",
    "timeline": "6–12 months",
    "salary": "$130k–$220k",
    "demand": "Very High"
  },
  {
    "slug": "ai-product-engineer",
    "title": "AI Product Engineer Learning Path",
    "description": "Bridge product thinking and AI engineering — the AI Product Engineer path covers building user-facing AI features, designing great AI UX, and shipping AI products end to end.",
    "timeline": "6–10 months",
    "salary": "$130k–$210k",
    "demand": "High"
  },
  {
    "slug": "ai-research-engineer",
    "title": "AI Research Engineer Learning Path",
    "description": "Go deep on the science of AI — the AI Research Engineer path covers mathematical foundations, novel architectures, paper implementation, and contributing to the frontier of AI research.",
    "timeline": "12–24 months",
    "salary": "$160k–$350k",
    "demand": "Moderate"
  },
  {
    "slug": "llm-engineer",
    "title": "LLM Engineer Learning Path",
    "description": "Master large language models from the inside out — the LLM Engineer path covers transformer architecture, fine-tuning, inference optimization, and deploying custom models at scale.",
    "timeline": "9–15 months",
    "salary": "$150k–$260k",
    "demand": "Very High"
  },
  {
    "slug": "ml-engineer",
    "title": "ML Engineer Learning Path",
    "description": "From data to deployed models — the ML Engineer path covers the full machine learning lifecycle: data pipelines, model training, evaluation, MLOps, and production serving.",
    "timeline": "8–14 months",
    "salary": "$140k–$230k",
    "demand": "High"
  }
];
