// AUTO-GENERATED by generate-content-data.js — do not edit manually
const BLOG_POSTS = [
  {
    "slug": "chain-of-thought-prompting",
    "title": "Chain-of-Thought Prompting Explained for Developers",
    "description": "A developer's guide to chain-of-thought prompting — how it works, when to use it, and production implementations including zero-shot CoT, self-consistency, and Tree of Thought.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "few-shot-vs-zero-shot",
    "title": "Few-Shot vs Zero-Shot Prompting Explained",
    "description": "Understand the practical differences between few-shot and zero-shot prompting — when to use each, how to write examples, and the cost vs. accuracy trade-offs.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-best-practices",
    "title": "Prompt Engineering Best Practices for Large Language Models",
    "description": "Production-tested prompt engineering best practices for LLMs — covering reliability, cost, structured output, evaluation, and prompt lifecycle management.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-examples",
    "title": "Prompt Engineering Examples for Real AI Applications",
    "description": "Practical prompt engineering examples for production AI use cases — classification, extraction, summarization, code review, RAG, and agent workflows.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-guide",
    "title": "Prompt Engineering Guide for AI Developers",
    "description": "A practical prompt engineering guide for developers. Learn techniques, patterns, and production best practices for working with modern LLMs in 2026.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-techniques",
    "title": "26 Prompt Engineering Techniques Every AI Developer Should Know (2026 Guide)",
    "description": "A complete reference of 26 prompt engineering techniques used in production AI systems — from zero-shot basics to agent loops and self-critique patterns.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "advanced-prompt-engineering",
    "title": "Advanced Prompt Engineering Techniques for LLMs",
    "description": "Learn advanced prompt engineering strategies including prompt chaining and tool use.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 8
  },
  {
    "slug": "ai-agents-guide",
    "title": "AI Agents Explained – How Autonomous AI Systems Work",
    "description": "Learn what AI agents are and how developers build autonomous AI systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "ai-learning-roadmap",
    "title": "AI Learning Roadmap for Developers (2026)",
    "description": "A step-by-step roadmap for developers to learn AI and build AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 8
  },
  {
    "slug": "ai-tools-for-developers",
    "title": "Best AI Tools for Developers in 2026",
    "description": "Explore the best AI tools developers use to build modern AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "attention-mechanism-explained",
    "title": "Attention Mechanism Explained in Simple Terms",
    "description": "Understand how attention mechanisms allow AI models to focus on relevant context.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-ai-agents",
    "title": "How to Build AI Agents Step-by-Step",
    "description": "Learn how developers build AI agents using LLM frameworks.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "build-ai-app",
    "title": "How to Build Your First AI Application",
    "description": "A practical guide for developers building AI-powered applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-rag-app",
    "title": "How to Build a RAG Application Step-by-Step",
    "description": "Learn how to build a Retrieval-Augmented Generation app using vector databases and LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "embeddings-explained",
    "title": "Embeddings Explained – How AI Understands Meaning",
    "description": "Understand embeddings and how they power semantic search and AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "few-shot-prompting-explained",
    "title": "Few-Shot Prompting Explained – Improve LLM Output",
    "description": "Understand how few-shot prompting works and how developers guide LLM responses.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "how-llms-work",
    "title": "How Large Language Models Work (Simple Guide)",
    "description": "Understand how large language models work including transformers and tokens.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "langchain-agents",
    "title": "LangChain Agents Explained for Developers",
    "description": "Learn how LangChain agents automate workflows in AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "langchain-tutorial",
    "title": "LangChain Tutorial – Build AI Applications with LLMs",
    "description": "Learn how to use LangChain to build AI applications with LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "llm-fine-tuning-guide",
    "title": "LLM Fine-Tuning Guide – Customize AI Models",
    "description": "Learn how developers fine-tune large language models.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "lora-fine-tuning-explained",
    "title": "LoRA Fine-Tuning Explained – Efficient LLM Training",
    "description": "Learn how LoRA fine-tuning works and why it is efficient.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "openai-api-tutorial",
    "title": "OpenAI API Tutorial for Developers",
    "description": "Learn how to use the OpenAI API to build AI-powered applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "openai-python-client-guide",
    "title": "OpenAI Python Client Guide – Chat, Embeddings, Tools",
    "description": "Learn how to use the OpenAI Python client to build AI apps.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "qlora-explained",
    "title": "QLoRA Explained – Efficient LLM Fine-Tuning",
    "description": "Learn how QLoRA reduces memory requirements when fine-tuning LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "rag-explained",
    "title": "RAG Explained – How Retrieval-Augmented Generation Works",
    "description": "Learn how Retrieval-Augmented Generation works and how developers build RAG systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "run-llms-locally",
    "title": "How to Run LLMs Locally Using Ollama",
    "description": "Learn how to run large language models locally using Ollama.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "transformer-architecture-explained",
    "title": "Transformer Architecture Explained for Developers",
    "description": "Learn how transformer models power modern AI systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "vector-database-explained",
    "title": "Vector Databases Explained – FAISS, Pinecone, Weaviate",
    "description": "Learn how vector databases power semantic search and AI retrieval systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "ai-agent-fundamentals",
    "title": "AI Agent Fundamentals: How LLM Agents Think, Plan, and Act",
    "description": "Learn the building blocks of AI agents — ReAct loops, tool use, planning, memory, and multi-agent coordination. Includes hands-on examples with LangChain and OpenAI.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "ai-application-architecture",
    "title": "AI Application Architecture: Designing Production-Ready LLM Systems",
    "description": "Architectural patterns for production AI applications — prompt management, context windows, fallback strategies, observability, cost control, and testing LLM systems.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 6
  },
  {
    "slug": "building-ai-chatbots",
    "title": "Building AI Chatbots: From Simple Q&A to Contextual Conversations",
    "description": "Step-by-step guide to building AI chatbots — multi-turn conversations, conversation memory, RAG-powered bots, streaming responses, and deploying a chat UI.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "deploying-ai-applications",
    "title": "Deploying AI Applications: From Local Dev to Production",
    "description": "Step-by-step guide to deploying AI applications — FastAPI serving, Docker containers, cloud deployment on AWS/GCP, model caching, rate limiting, and monitoring.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "document-chunking-strategies",
    "title": "Document Chunking Strategies for RAG: How to Split Text for Better Retrieval",
    "description": "Learn the best document chunking strategies for RAG — fixed size, sentence, semantic, and hierarchical chunking. Includes benchmarks and code for each approach.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "feature-engineering-guide",
    "title": "Feature Engineering Guide: Transform Raw Data into Model-Ready Features",
    "description": "Practical feature engineering techniques for ML engineers — encoding, scaling, handling missing values, creating new features, and selecting the most useful ones.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "fine-tuning-llms-guide",
    "title": "Fine-Tuning LLMs: Complete Guide to Instruction Tuning and LoRA",
    "description": "Learn how to fine-tune large language models — full fine-tuning vs LoRA vs QLoRA, dataset preparation, training with Hugging Face, and avoiding common pitfalls.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "langchain-rag-tutorial",
    "title": "LangChain RAG Tutorial: Build a Document Q&A System Step by Step",
    "description": "Build a complete RAG pipeline with LangChain — document loading, text splitting, vector store indexing, retrieval chains, and conversational Q&A with memory.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "langchain-tutorial-complete",
    "title": "LangChain Complete Tutorial: Chains, Agents, Tools, and Memory",
    "description": "Master LangChain from scratch — LLM wrappers, prompt templates, chains, LCEL, agents with tools, memory, and building production applications.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "llm-inference-and-serving",
    "title": "LLM Inference and Serving: vLLM, Ollama, and Production Optimization",
    "description": "Guide to LLM inference optimization — KV cache, continuous batching, quantization, vLLM serving, Ollama local deployment, and benchmarking throughput and latency.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "machine-learning-basics-for-developers",
    "title": "Machine Learning Basics for Developers: A Practical Introduction",
    "description": "A developer-first introduction to machine learning — core concepts, types of ML, hands-on Python workflow, and how to go from data to a working model.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "model-evaluation-and-metrics",
    "title": "Model Evaluation and Metrics: How to Measure ML Model Performance",
    "description": "Complete guide to ML evaluation metrics — accuracy, precision, recall, F1, AUC-ROC, RMSE, confusion matrices, learning curves, and cross-validation strategies.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "multi-agent-systems",
    "title": "Multi-Agent Systems: Architectures for Coordinating LLM Agents",
    "description": "Build multi-agent AI systems — orchestrator-worker patterns, agent handoffs, shared memory, debate patterns, and production-ready multi-agent orchestration with LangGraph.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "open-source-llms-guide",
    "title": "Open Source LLMs Guide: Llama, Mistral, Gemma, and How to Run Them Locally",
    "description": "Compare the top open source LLMs — Llama 3, Mistral, Gemma, Phi — and learn how to run them locally with Ollama, llama.cpp, and Hugging Face Transformers.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "openai-api-complete-guide",
    "title": "OpenAI API Complete Guide: Chat, Embeddings, Functions, and Streaming",
    "description": "Master the OpenAI API — chat completions, function calling, embeddings, streaming responses, error handling, cost optimization, and building production-ready integrations.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "python-for-machine-learning",
    "title": "Python for Machine Learning: NumPy, Pandas, and Scikit-learn Essentials",
    "description": "The Python toolkit every ML engineer needs — NumPy arrays, pandas DataFrames, data visualization with matplotlib, and scikit-learn's core API.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "rag-system-architecture",
    "title": "RAG System Architecture: Design Patterns for Production Retrieval-Augmented Generation",
    "description": "Architecture guide for production RAG systems — naive RAG vs advanced RAG, indexing pipelines, hybrid search, reranking, guardrails, and performance optimization.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "supervised-learning-guide",
    "title": "Supervised Learning Guide: Algorithms, Workflows, and Best Practices",
    "description": "Deep dive into supervised learning — regression and classification algorithms, evaluation metrics, cross-validation, and how to pick the right model for your problem.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "tool-use-and-function-calling",
    "title": "Tool Use and Function Calling in LLMs: Practical Patterns and Best Practices",
    "description": "Complete guide to LLM function calling — defining tools, parallel tool calls, error handling, designing reliable tool schemas, and building agentic pipelines.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "vector-database-guide",
    "title": "Vector Database Guide: Embeddings, Similarity Search, and Choosing the Right DB",
    "description": "Complete guide to vector databases — how embeddings work, similarity search algorithms, HNSW indexing, and a comparison of Pinecone, Weaviate, Qdrant, Chroma, and pgvector.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ai-roadmap-for-developers",
    "title": "AI Roadmap for Developers 2026: The Complete Learning Path",
    "description": "The definitive AI learning roadmap for software developers in 2026. Follow 7 phases from AI foundations to building and shipping real AI projects — with free resources and milestone projects.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 7
  },
  {
    "slug": "how-to-become-ai-engineer",
    "title": "How to Become an AI Engineer in 2026 (From Any Background)",
    "description": "A practical guide to becoming an AI engineer in 2026. Learn what skills you need, how long it takes, what to build, and how to land your first AI engineering role — from any starting point.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 5
  },
  {
    "slug": "machine-learning-roadmap",
    "title": "Machine Learning Roadmap 2026: From Beginner to Job-Ready",
    "description": "The complete machine learning roadmap for 2026. Learn Python, math fundamentals, classical ML, deep learning, LLMs, and MLOps — with free resources and project milestones at each stage.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 6
  },
  {
    "slug": "rag-tutorial-step-by-step",
    "title": "RAG Tutorial 2026: Build a Retrieval-Augmented Generation Pipeline from Scratch",
    "description": "Step-by-step RAG tutorial for developers in 2026. Build a complete Retrieval-Augmented Generation pipeline — document loading, chunking, vector embeddings, semantic search, and LLM generation with LangChain and ChromaDB.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 5
  }
];
const ROADMAP_GUIDES = [
  {
    "slug": "ai-agent-evaluation",
    "title": "AI Agent Evaluation: Testing, Benchmarking, and Safety for Agentic Systems",
    "description": "Learn how to rigorously evaluate AI agents — building test suites, measuring task completion rates, detecting failures, red-teaming, and implementing safety guardrails for production deployments.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ai-foundations-for-developers",
    "title": "AI Foundations for Developers: Core Concepts You Must Know",
    "description": "A developer-focused introduction to AI fundamentals: what AI, ML, and deep learning actually are, how they differ, and the mental models you need before writing your first AI application.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "building-ai-agents-guide",
    "title": "Building AI Agents: ReAct, Tool Use, and Agentic Workflows",
    "description": "A practical guide to building AI agents that can reason and act — covering the ReAct pattern, tool definition, agent loops, memory strategies, and multi-step task execution with OpenAI function calling.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "deep-learning-fundamentals",
    "title": "Deep Learning Fundamentals: CNNs, RNNs, and the Road to Transformers",
    "description": "Understand the deep learning architectures that shaped modern AI — convolutional networks for images, recurrent networks for sequences, and how their limitations led to the transformer revolution.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "how-llms-work",
    "title": "How LLMs Work: From Pretraining to ChatGPT — A Developer's Guide",
    "description": "A technical deep dive into how large language models actually work — tokenization, pretraining, RLHF, inference, and the architectural decisions that define modern LLMs like GPT-4 and Claude.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 6
  },
  {
    "slug": "linear-algebra-for-ai",
    "title": "Linear Algebra for AI Developers: The Concepts That Actually Matter",
    "description": "A practical guide to the linear algebra used in AI and machine learning — vectors, matrices, dot products, and matrix multiplication explained with Python code and real AI use cases.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ml-project-workflow",
    "title": "ML Project Workflow: End-to-End Machine Learning in Practice",
    "description": "A practical guide to the full machine learning project lifecycle — problem framing, data collection, feature engineering, model selection, evaluation, and deployment — with Python code at every step.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "neural-networks-from-scratch",
    "title": "Neural Networks from Scratch: Build One in Pure Python",
    "description": "Build a neural network from scratch using only NumPy to understand how forward passes, backpropagation, and gradient descent actually work. No frameworks, just the math made concrete.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "production-rag-best-practices",
    "title": "Production RAG Best Practices: Chunking, Reranking, and Evaluation",
    "description": "Go beyond basic RAG with advanced techniques: recursive chunking strategies, metadata filtering, reranking retrieved documents, evaluating RAG pipelines, and building production-ready retrieval systems.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "python-for-ai-complete-guide",
    "title": "Python for AI Developers: Complete Setup and Essential Libraries",
    "description": "Set up a production-ready Python AI development environment. Covers virtual environments, essential libraries (NumPy, pandas, OpenAI SDK), Jupyter notebooks, and common patterns used in AI projects.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "pytorch-for-ai-developers",
    "title": "PyTorch for AI Developers: Practical Guide from Tensors to Training",
    "description": "A hands-on PyTorch guide covering tensors, autograd, model building with nn.Module, training loops, GPU acceleration, and loading pre-trained models from HuggingFace.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "semantic-search-explained",
    "title": "Semantic Search Explained: How Embeddings Enable Meaning-Based Search",
    "description": "Understand how semantic search works — from text embeddings and vector spaces to HNSW indexes and approximate nearest neighbor search. Build a production-quality semantic search engine in Python.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "statistics-for-machine-learning",
    "title": "Statistics for Machine Learning: Practical Concepts for Developers",
    "description": "The statistical concepts that actually matter for ML practitioners — probability distributions, Bayes' theorem, hypothesis testing, and how to interpret model evaluation metrics correctly.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "working-with-local-llms",
    "title": "Working with Local LLMs: Run AI Models Privately with Ollama and llama.cpp",
    "description": "Run powerful LLMs completely offline on your own hardware. Set up Ollama, run Llama 3, Mistral, and Code Llama locally, build Python integrations, and understand when to use local vs API models.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  }
];
const PROJECT_LIST = [
  {
    "slug": "ai-chatbot-python",
    "title": "Build an AI Chatbot in Python: Complete Beginner Project",
    "description": "Build a multi-turn AI chatbot in Python using the OpenAI API. Includes conversation memory, streaming, a CLI interface, and a simple Gradio web UI.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Gradio"
  },
  {
    "slug": "ai-code-explainer",
    "title": "Build an AI Code Explainer: Understand Any Code Instantly",
    "description": "Build a tool that explains code in plain English, identifies bugs, suggests improvements, and generates documentation — for any programming language.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Click"
  },
  {
    "slug": "ai-email-writer",
    "title": "Build an AI Email Writer: Draft Professional Emails in Seconds",
    "description": "Build an AI tool that drafts professional emails from bullet points or brief descriptions. Supports multiple tones, templates, and a Streamlit web UI.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Streamlit"
  },
  {
    "slug": "ai-quiz-generator",
    "title": "Build an AI Quiz Generator from Any Text or Document",
    "description": "Build an AI tool that generates multiple-choice quizzes from any text, PDF, or topic. Export to JSON, run interactively, and track scores.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, JSON"
  },
  {
    "slug": "ai-resume-analyzer",
    "title": "Build an AI Resume Analyzer: Score, Critique, and Improve Resumes",
    "description": "Build a tool that analyzes resumes against job descriptions, scores fit, identifies gaps, and suggests specific improvements using GPT-4o-mini.",
    "level": "Beginner",
    "time": "3–4 hours",
    "stack": "Python, OpenAI API, pypdf, Streamlit"
  },
  {
    "slug": "build-chatgpt-clone",
    "title": "Build a ChatGPT Clone from Scratch: Full-Stack AI Chat App",
    "description": "Build a full-stack conversational AI app with streaming responses, persistent conversation history, and a React chat UI — using FastAPI and the OpenAI API.",
    "level": "Beginner",
    "time": "3–4 hours",
    "stack": "Python, FastAPI, React, OpenAI API"
  },
  {
    "slug": "document-summarizer",
    "title": "Build an AI Document Summarizer: PDF, Text, and URL Summarization",
    "description": "Build an AI-powered document summarizer that handles PDFs, plain text, and web URLs. Supports map-reduce summarization for long documents and outputs key bullet points.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, PyPDF2, BeautifulSoup"
  },
  {
    "slug": "sentiment-analyzer",
    "title": "Build an AI Sentiment Analyzer: Classify Text Sentiment and Emotions",
    "description": "Build a sentiment analysis tool using GPT-4o-mini that classifies text as positive, negative, or neutral, detects emotions, and processes batches of reviews or tweets.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, pandas"
  },
  {
    "slug": "ai-content-moderator",
    "title": "Build an AI Content Moderator: Classify and Filter Harmful Content",
    "description": "Build a content moderation system that classifies text and images for toxicity, hate speech, spam, and policy violations. Includes a review queue and confidence thresholds.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API (Moderation + GPT), FastAPI, SQLite"
  },
  {
    "slug": "ai-data-analyst",
    "title": "Build an AI Data Analyst: Chat with Your CSV Data",
    "description": "Build a natural language data analysis tool that lets you ask questions about CSV datasets. Generates and executes Python pandas code, produces charts, and explains insights automatically.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API, pandas, matplotlib, Streamlit"
  },
  {
    "slug": "ai-meeting-summarizer",
    "title": "Build an AI Meeting Summarizer: Transcribe and Summarize Meetings Automatically",
    "description": "Build a tool that transcribes audio recordings with Whisper, summarizes with GPT-4o-mini, extracts action items, decisions, and attendee contributions into a structured meeting report.",
    "level": "Intermediate",
    "time": "3–5 hours",
    "stack": "Python, OpenAI API (Whisper + GPT), Streamlit"
  },
  {
    "slug": "ai-research-assistant",
    "title": "Build an AI Research Assistant: Summarize Papers and Extract Insights",
    "description": "Build an AI tool that reads academic papers and web pages, extracts key findings, compares multiple sources, and generates research summaries with citations.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API, requests, BeautifulSoup, Streamlit"
  },
  {
    "slug": "ai-support-bot",
    "title": "Build an AI Customer Support Bot with Knowledge Base",
    "description": "Build a production-ready customer support chatbot that answers questions from your documentation, escalates complex issues, maintains conversation history, and handles tone appropriately.",
    "level": "Intermediate",
    "time": "5–6 hours",
    "stack": "Python, OpenAI API, ChromaDB, FastAPI, Streamlit"
  },
  {
    "slug": "rag-document-assistant",
    "title": "Build a RAG Document Assistant: Chat with Your Documents",
    "description": "Build a Retrieval-Augmented Generation system that lets you upload documents and ask questions. Uses embeddings, vector search, and GPT-4o-mini for accurate, grounded answers.",
    "level": "Intermediate",
    "time": "4–6 hours",
    "stack": "Python, OpenAI API, ChromaDB, Streamlit"
  },
  {
    "slug": "voice-ai-assistant",
    "title": "Build a Voice AI Assistant: Speech-to-Speech Conversational AI",
    "description": "Build a voice-enabled AI assistant using Whisper for speech recognition, GPT-4o-mini for responses, and TTS for natural voice output. Supports wake word detection and conversation memory.",
    "level": "Intermediate",
    "time": "4–6 hours",
    "stack": "Python, OpenAI API (Whisper + GPT + TTS), sounddevice, pygame"
  },
  {
    "slug": "ai-code-review-assistant",
    "title": "Build an AI Code Review Assistant: Automated PR Reviews",
    "description": "Build a tool that reviews Git diffs and pull requests, identifies bugs, security issues, style violations, and suggests improvements — integrated with GitHub Actions.",
    "level": "Advanced",
    "time": "6–8 hours",
    "stack": "Python, OpenAI API, GitHub API, FastAPI"
  },
  {
    "slug": "ai-personal-knowledge-base",
    "title": "Build an AI Personal Knowledge Base: Your Second Brain with AI",
    "description": "Build a personal knowledge management system that ingests notes, web clips, and PDFs, auto-links related content, and lets you have conversations with your accumulated knowledge.",
    "level": "Advanced",
    "time": "8–12 hours",
    "stack": "Python, OpenAI API, ChromaDB, SQLite, Streamlit"
  },
  {
    "slug": "ai-sales-agent",
    "title": "Build an AI Sales Agent: Automated Lead Qualification and Outreach",
    "description": "Build an AI sales agent that qualifies leads from a CRM, personalizes outreach emails based on company research, tracks responses, and generates pipeline reports.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, SQLite, FastAPI, requests"
  },
  {
    "slug": "ai-security-analyzer",
    "title": "Build an AI Security Analyzer: Automated Vulnerability Detection",
    "description": "Build a static analysis tool that scans codebases for security vulnerabilities using GPT-4o-mini, detecting OWASP Top 10 issues, secrets in code, and insecure patterns with severity scoring.",
    "level": "Advanced",
    "time": "6–8 hours",
    "stack": "Python, OpenAI API, GitPython, Click"
  },
  {
    "slug": "ai-study-planner",
    "title": "Build an AI Study Planner: Personalized Learning Schedules with Spaced Repetition",
    "description": "Build an AI study planner that creates personalized schedules, generates practice questions using spaced repetition, tracks progress, and adapts the plan based on performance.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, SQLite, Streamlit, schedule"
  },
  {
    "slug": "multi-agent-research-system",
    "title": "Build a Multi-Agent Research System: Parallel AI Agents for Deep Research",
    "description": "Build a multi-agent system where a Planner agent breaks research questions into sub-tasks, Researcher agents gather information in parallel, and a Synthesizer agent produces a comprehensive report.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, asyncio, Tavily Search API, Streamlit"
  }
];
const PATH_LIST = [
  {
    "slug": "ai-engineer",
    "title": "AI Engineer Learning Path",
    "description": "A complete roadmap to becoming an AI Engineer — the generalist role that designs, builds, and ships AI-powered applications and systems in production.",
    "timeline": "6–12 months",
    "salary": "$130k–$220k",
    "demand": "Very High"
  },
  {
    "slug": "ai-product-engineer",
    "title": "AI Product Engineer Learning Path",
    "description": "Bridge product thinking and AI engineering — the AI Product Engineer path covers building user-facing AI features, designing great AI UX, and shipping AI products end to end.",
    "timeline": "6–10 months",
    "salary": "$130k–$210k",
    "demand": "High"
  },
  {
    "slug": "ai-research-engineer",
    "title": "AI Research Engineer Learning Path",
    "description": "Go deep on the science of AI — the AI Research Engineer path covers mathematical foundations, novel architectures, paper implementation, and contributing to the frontier of AI research.",
    "timeline": "12–24 months",
    "salary": "$160k–$350k",
    "demand": "Moderate"
  },
  {
    "slug": "llm-engineer",
    "title": "LLM Engineer Learning Path",
    "description": "Master large language models from the inside out — the LLM Engineer path covers transformer architecture, fine-tuning, inference optimization, and deploying custom models at scale.",
    "timeline": "9–15 months",
    "salary": "$150k–$260k",
    "demand": "Very High"
  },
  {
    "slug": "ml-engineer",
    "title": "ML Engineer Learning Path",
    "description": "From data to deployed models — the ML Engineer path covers the full machine learning lifecycle: data pipelines, model training, evaluation, MLOps, and production serving.",
    "timeline": "8–14 months",
    "salary": "$140k–$230k",
    "demand": "High"
  }
];
