// AUTO-GENERATED by generate-content-data.js — do not edit manually
const BLOG_POSTS = [
  {
    "slug": "synthetic-data-llm",
    "title": "Synthetic Data for LLM Fine-Tuning: Generate Training Data with GPT-4o",
    "description": "Generate high-quality synthetic training data for LLM fine-tuning using GPT-4o — self-instruct, Evol-Instruct, quality filtering, and a complete dataset generation pipeline.",
    "date": "2026-03-23",
    "date_display": "March 23, 2026",
    "mins": 10
  },
  {
    "slug": "rlhf-guide",
    "title": "RLHF Explained: How Reinforcement Learning from Human Feedback Works (2026)",
    "description": "Understand RLHF — the SFT to reward model to PPO pipeline, DPO as a simpler alternative, TRL DPOTrainer code, and practical challenges of reward hacking.",
    "date": "2026-03-22",
    "date_display": "March 22, 2026",
    "mins": 9
  },
  {
    "slug": "openai-langchain",
    "title": "OpenAI + LangChain: Build Production AI Apps with GPT-4o (2026)",
    "description": "Build production AI apps with OpenAI GPT-4o and LangChain — LCEL chains, memory, RAG pipelines, and tool-using agents with real Python examples.",
    "date": "2026-03-21",
    "date_display": "March 21, 2026",
    "mins": 8
  },
  {
    "slug": "open-vs-closed-llm",
    "title": "Open Source vs Closed LLMs: Which Should You Use in Production? (2026)",
    "description": "Practical guide to choosing between open source and closed LLMs for production — cost, capability, privacy, fine-tuning control, and vendor lock-in trade-offs.",
    "date": "2026-03-20",
    "date_display": "March 20, 2026",
    "mins": 9
  },
  {
    "slug": "open-source-llm-guide",
    "title": "Open Source LLMs: Complete Developer Guide to Self-Hosted AI (2026)",
    "description": "Complete developer guide to open source LLMs — model families, local runtimes, quantization formats, hardware requirements, and deploying self-hosted AI in production.",
    "date": "2026-03-19",
    "date_display": "March 19, 2026",
    "mins": 12
  },
  {
    "slug": "open-source-llm-comparison",
    "title": "Open Source LLM Comparison: Llama 3 vs Mistral vs Phi-4 vs Gemma (2026)",
    "description": "Compare the top open source LLMs for 2026 — Llama 3, Mistral, Phi-4, and Gemma on benchmarks, hardware requirements, and real-world task performance.",
    "date": "2026-03-18",
    "date_display": "March 18, 2026",
    "mins": 10
  },
  {
    "slug": "ollama-tutorial",
    "title": "Ollama Tutorial: Run Llama 3, Mistral & Gemma Locally in 10 Minutes (2026)",
    "description": "Get started with Ollama in 10 minutes — install, pull models like Llama 3 and Mistral, integrate with Python, build a local chatbot, and use custom Modelfiles.",
    "date": "2026-03-17",
    "date_display": "March 17, 2026",
    "mins": 9
  },
  {
    "slug": "model-distillation",
    "title": "LLM Knowledge Distillation: Create Small, Fast Models from Large Ones (2026)",
    "description": "Learn how knowledge distillation creates small, fast LLMs from large teacher models — teacher-student training, response distillation, and Python implementation examples.",
    "date": "2026-03-16",
    "date_display": "March 16, 2026",
    "mins": 9
  },
  {
    "slug": "ai-agents-guide",
    "title": "AI Agents Guide: Architecture and Design Patterns",
    "description": "Complete guide to AI agent architecture — perception, planning, memory, tool use, and execution loops for senior engineers building production systems.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "ann-algorithms",
    "title": "Approximate Nearest Neighbor Algorithms Explained",
    "description": "How ANN algorithms work — HNSW, IVF, ScaNN, and PQ explained with code, benchmarks, and tradeoffs for building fast vector search at scale.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "chain-of-thought-prompting",
    "title": "Chain-of-Thought Prompting Explained for Developers",
    "description": "A developer's guide to chain-of-thought prompting — how it works, when to use it, and production implementations including zero-shot CoT, self-consistency, and Tree of Thought.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "context-window-rag",
    "title": "Context Window Optimization in RAG Systems",
    "description": "Learn how to optimize context window usage in RAG systems. Covers chunk selection, context compression, reranking, and prompt design to maximize LLM answer quality.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "embedding-model-comparison",
    "title": "Embedding Model Comparison for Vector Search",
    "description": "Compare OpenAI, BGE, E5, Cohere, and Voyage embedding models for vector search — benchmarks, pricing, dimensions, and which to use for production RAG.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "embeddings-explained",
    "title": "Embeddings Explained: How AI Understands Text",
    "description": "Deep dive into AI embeddings — how models convert text to vectors, which models to choose, how similarity works, and how to use embeddings in production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "few-shot-vs-zero-shot",
    "title": "Few-Shot vs Zero-Shot Prompting Explained",
    "description": "Understand the practical differences between few-shot and zero-shot prompting — when to use each, how to write examples, and the cost vs. accuracy trade-offs.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "hybrid-search-rag",
    "title": "Hybrid Search in RAG Systems",
    "description": "Learn how hybrid search combines vector and keyword search in RAG systems to improve retrieval precision for technical and domain-specific content.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "langchain-agents",
    "title": "Building Agents with LangChain: Complete Tutorial",
    "description": "Build a LangChain agent from scratch — AgentExecutor, tools, ReAct prompting. Working code for a research agent with DuckDuckGo, Wikipedia, and Python REPL.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "llm-fine-tuning-guide",
    "title": "LLM Fine-Tuning Guide: LoRA, QLoRA, and Full Fine-Tuning",
    "description": "Complete guide to LLM fine-tuning: when to use LoRA vs QLoRA vs full fine-tuning, dataset prep, training infra, and evaluation with TRL and Unsloth.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 10
  },
  {
    "slug": "lora-fine-tuning-tutorial",
    "title": "LoRA Fine-Tuning Tutorial: Train Custom LLMs on a Single GPU (2026)",
    "description": "Step-by-step LoRA fine-tuning tutorial — train a custom LLM on a single consumer GPU using PEFT, Unsloth, and TRL, from dataset prep to merged model deployment.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "multi-agent-systems",
    "title": "Multi-Agent Systems Explained",
    "description": "Multi-agent coordination patterns — supervisor-worker, peer-to-peer, hierarchical. When to use multi-agent vs single agent, with CrewAI and LangGraph examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "multi-document-rag",
    "title": "Multi-Document RAG: Search Across 100+ Sources Without Wrong Answers (2026)",
    "description": "Stop getting wrong answers from flat vector stores. Learn routing, namespace filtering, and cross-document fusion to build RAG that works across hundreds of documents.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "openai-api-tutorial",
    "title": "OpenAI API Tutorial for Developers (2026)",
    "description": "Complete OpenAI API tutorial — setup, chat completions, streaming, function calling, embeddings, vision, token counting, error handling, and retry logic for 2026.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 14
  },
  {
    "slug": "production-rag",
    "title": "Production RAG System Design",
    "description": "Design and deploy production RAG systems that handle real traffic. Covers architecture, caching, monitoring, scaling, and reliability patterns for RAG in production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-best-practices",
    "title": "Prompt Engineering Best Practices for Large Language Models",
    "description": "Production-tested prompt engineering best practices for LLMs — covering reliability, cost, structured output, evaluation, and prompt lifecycle management.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-examples",
    "title": "Prompt Engineering Examples for Real AI Applications",
    "description": "Practical prompt engineering examples for production AI use cases — classification, extraction, summarization, code review, RAG, and agent workflows.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-guide",
    "title": "Prompt Engineering Guide for AI Developers",
    "description": "A practical prompt engineering guide for developers. Learn techniques, patterns, and production best practices for working with modern LLMs in 2026.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-engineering-mistakes",
    "title": "Common Prompt Engineering Mistakes Developers Make",
    "description": "The most common prompt engineering mistakes developers make in production — and how to fix them with concrete, actionable techniques.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-engineering-techniques",
    "title": "17 Prompt Engineering Techniques Every AI Developer Should Know (2026)",
    "description": "17 foundational prompt engineering techniques with Python examples — zero-shot, few-shot, chain-of-thought, constrained output, RAG prompting, and more. Built for production AI systems.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "prompt-injection",
    "title": "Prompt Injection Attacks and How to Prevent Them",
    "description": "Understand prompt injection attacks — how they work, real-world examples, and practical defenses for production LLM applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "prompt-templates",
    "title": "Prompt Templates for AI Applications",
    "description": "Learn how to build reusable, maintainable prompt templates for production AI applications — covering parameterization, versioning, and testing patterns.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 7
  },
  {
    "slug": "qlora-explained",
    "title": "QLoRA Explained: Efficient LLM Fine-Tuning on Consumer Hardware",
    "description": "QLoRA combines 4-bit NF4 quantization with LoRA adapters to fine-tune 13B+ LLMs on a single GPU. Complete guide with BitsAndBytes, PEFT, and TRL code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "rag-architecture-guide",
    "title": "RAG Architecture Guide for AI Developers",
    "description": "A complete guide to retrieval augmented generation architecture — how RAG systems work, when to use them, and how to build them for production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 11
  },
  {
    "slug": "rag-chatbot",
    "title": "Build a RAG Chatbot with Python and Vector Databases",
    "description": "Build a RAG chatbot with Python, LangChain, and ChromaDB. Add conversation memory, source citations, and streaming — with production-ready code examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "rag-chunking-strategies",
    "title": "Chunking Strategies for RAG Pipelines",
    "description": "Learn the best chunking strategies for RAG pipelines. Compare fixed-size, semantic, and recursive chunking with Python code examples and practical tuning guidance.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "rag-evaluation",
    "title": "RAG Evaluation: Measure Faithfulness, Relevancy & Context Quality (2026)",
    "description": "RAG looks good in testing but fails in production? Learn the 4 RAGAS metrics — faithfulness, relevancy, context precision, recall — with working Python examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "rag-tutorial",
    "title": "RAG Tutorial: Build Retrieval-Augmented Generation Systems (2026)",
    "description": "Step-by-step RAG tutorial for developers. Build a complete retrieval-augmented generation system using LangChain, OpenAI, and ChromaDB with runnable Python code.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "rag-vs-finetuning",
    "title": "RAG vs Fine-Tuning: When to Use Each",
    "description": "Understand when to use RAG vs fine-tuning for LLM applications. Compare cost, latency, accuracy, and maintenance for each approach with real engineering examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "role-prompting",
    "title": "Role Prompting Explained for LLMs",
    "description": "Learn how role prompting shapes LLM outputs — when persona assignment improves results, how to write effective role prompts, and the trade-offs to know.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "semantic-search-vector",
    "title": "Semantic Search with Vector Databases",
    "description": "Build production semantic search with vector databases — hybrid BM25 + vector search, re-ranking, metadata filtering, and real Python examples with ChromaDB.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "system-prompts-guide",
    "title": "System Prompts: How to Control LLM Behavior",
    "description": "Learn how to write effective system prompts that control LLM tone, persona, output format, and safety constraints across production AI applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "vector-database-comparison",
    "title": "Vector Databases Explained: Chroma vs Pinecone vs FAISS (2026)",
    "description": "Hands-on comparison of Chroma, Pinecone, FAISS, Weaviate, and pgvector — performance, pricing, and when to choose each for AI applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 7
  },
  {
    "slug": "vector-database-guide",
    "title": "Vector Databases Guide for AI Applications",
    "description": "Complete guide to vector databases for AI apps — embeddings, similarity search, HNSW indexing, and how to pick the right vector DB for production.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-database-scaling",
    "title": "Scaling Vector Databases in Production",
    "description": "How to scale vector databases for production — sharding, replication, query optimization, caching, and architecture patterns for high-throughput AI apps.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-indexing",
    "title": "Vector Indexing Techniques Explained",
    "description": "Vector indexing from flat to HNSW, IVF, and PQ — how each technique works, when to use it, and Python examples with FAISS and ChromaDB.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-recommendation-systems",
    "title": "Building Recommendation Systems with Vector Search",
    "description": "Build production recommendation systems using vector search — item embeddings, collaborative filtering with vectors, two-tower models, and real Python examples.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "vector-search-explained",
    "title": "Vector Search Explained for AI Developers",
    "description": "How vector search works under the hood — embeddings, distance metrics, ANN algorithms, and building a production semantic search system step by step.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-vs-keyword-search",
    "title": "Vector Search vs Keyword Search in RAG",
    "description": "Compare vector search vs keyword search for RAG systems. Understand when semantic search beats BM25, when it fails, and how to choose the right retrieval strategy.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 8
  },
  {
    "slug": "vector-vs-relational-db",
    "title": "Vector Database vs Traditional Database",
    "description": "Vector database vs relational database — when to use each, how they differ architecturally, and practical guidance on hybrid approaches for AI applications.",
    "date": "2026-03-15",
    "date_display": "March 15, 2026",
    "mins": 9
  },
  {
    "slug": "local-ai-development",
    "title": "Local AI Development: Run LLMs Offline with Ollama, llama.cpp & LM Studio",
    "description": "Set up a complete local AI development environment — run LLMs offline with Ollama, llama.cpp, and LM Studio, no API keys or cloud required, with Python examples.",
    "date": "2026-03-14",
    "date_display": "March 14, 2026",
    "mins": 8
  },
  {
    "slug": "advanced-prompt-engineering",
    "title": "Advanced Prompt Engineering: ReAct, Tree of Thought & Agent Patterns (2026)",
    "description": "Master advanced prompt engineering techniques — ReAct, plan-and-solve, Tree of Thought, self-critique, meta-prompting, and prompt ensembling. Patterns used in production AI agents and multi-step workflows.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 13
  },
  {
    "slug": "ai-learning-roadmap",
    "title": "AI Learning Roadmap for Developers (2026)",
    "description": "A step-by-step roadmap for developers to learn AI and build AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 8
  },
  {
    "slug": "ai-tools-for-developers",
    "title": "Best AI Tools for Developers in 2026",
    "description": "Explore the best AI tools developers use to build modern AI applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "attention-mechanism-explained",
    "title": "Attention Mechanism Explained in Simple Terms",
    "description": "Understand how attention mechanisms allow AI models to focus on relevant context.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-ai-agents",
    "title": "How to Build AI Agents Step-by-Step",
    "description": "Learn how developers build AI agents using LLM frameworks.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-ai-app",
    "title": "How to Build Your First AI Application",
    "description": "A practical guide for developers building AI-powered applications.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "build-rag-app",
    "title": "How to Build a RAG Application Step-by-Step",
    "description": "Learn how to build a Retrieval-Augmented Generation app using vector databases and LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "few-shot-prompting-explained",
    "title": "Few-Shot Prompting Explained – Improve LLM Output",
    "description": "Understand how few-shot prompting works and how developers guide LLM responses.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "how-llms-work",
    "title": "How Large Language Models Work (Simple Guide)",
    "description": "Understand how large language models work including transformers and tokens.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "langchain-tutorial",
    "title": "LangChain Tutorial – Build AI Applications with LLMs",
    "description": "Learn how to use LangChain to build AI applications with LLMs.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 7
  },
  {
    "slug": "lora-fine-tuning-explained",
    "title": "LoRA Fine-Tuning Explained – Efficient LLM Training",
    "description": "Learn how LoRA fine-tuning works and why it is efficient.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "openai-python-client-guide",
    "title": "OpenAI Python Client Guide – Chat, Embeddings, Tools",
    "description": "Learn how to use the OpenAI Python client to build AI apps.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "rag-explained",
    "title": "RAG Explained – How Retrieval-Augmented Generation Works",
    "description": "Learn how Retrieval-Augmented Generation works and how developers build RAG systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 6
  },
  {
    "slug": "run-llms-locally",
    "title": "How to Run LLMs Locally Using Ollama",
    "description": "Learn how to run large language models locally using Ollama.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "transformer-architecture-explained",
    "title": "Transformer Architecture Explained for Developers",
    "description": "Learn how transformer models power modern AI systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "vector-database-explained",
    "title": "Vector Databases Explained – FAISS, Pinecone, Weaviate",
    "description": "Learn how vector databases power semantic search and AI retrieval systems.",
    "date": "2026-03-13",
    "date_display": "March 13, 2026",
    "mins": 5
  },
  {
    "slug": "llm-streaming",
    "title": "LLM Streaming: Stream Token-by-Token Responses with OpenAI & FastAPI",
    "description": "Implement LLM streaming in Python — stream token-by-token responses with OpenAI, build a FastAPI SSE backend, and handle streaming errors and backpressure.",
    "date": "2026-03-12",
    "date_display": "March 12, 2026",
    "mins": 9
  },
  {
    "slug": "llm-rate-limits",
    "title": "LLM Rate Limits: Handle Token Limits and API Throttling in Python (2026)",
    "description": "Handle LLM API rate limits in production — TPM and RPM limits, exponential backoff with jitter, token bucket rate limiting, and queue-based throttling in Python.",
    "date": "2026-03-11",
    "date_display": "March 11, 2026",
    "mins": 9
  },
  {
    "slug": "ai-agent-fundamentals",
    "title": "AI Agent Fundamentals: How LLM Agents Think, Plan, and Act",
    "description": "Learn the building blocks of AI agents — ReAct loops, tool use, planning, memory, and multi-agent coordination. Includes hands-on examples with LangChain and OpenAI.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "ai-application-architecture",
    "title": "AI Application Architecture: Designing Production-Ready LLM Systems",
    "description": "Architectural patterns for production AI applications — prompt management, context windows, fallback strategies, observability, cost control, and testing LLM systems.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 6
  },
  {
    "slug": "building-ai-chatbots",
    "title": "Building AI Chatbots: From Simple Q&A to Contextual Conversations",
    "description": "Step-by-step guide to building AI chatbots — multi-turn conversations, conversation memory, RAG-powered bots, streaming responses, and deploying a chat UI.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "deploying-ai-applications",
    "title": "Deploying AI Applications: From Local Dev to Production",
    "description": "Step-by-step guide to deploying AI applications — FastAPI serving, Docker containers, cloud deployment on AWS/GCP, model caching, rate limiting, and monitoring.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "document-chunking-strategies",
    "title": "Document Chunking Strategies for RAG: How to Split Text for Better Retrieval",
    "description": "Learn the best document chunking strategies for RAG — fixed size, sentence, semantic, and hierarchical chunking. Includes benchmarks and code for each approach.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "feature-engineering-guide",
    "title": "Feature Engineering Guide: Transform Raw Data into Model-Ready Features",
    "description": "Practical feature engineering techniques for ML engineers — encoding, scaling, handling missing values, creating new features, and selecting the most useful ones.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "fine-tuning-llms-guide",
    "title": "Fine-Tuning LLMs: Complete Guide to Instruction Tuning and LoRA",
    "description": "Learn how to fine-tune large language models — full fine-tuning vs LoRA vs QLoRA, dataset preparation, training with Hugging Face, and avoiding common pitfalls.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 8
  },
  {
    "slug": "langchain-rag-tutorial",
    "title": "LangChain RAG Tutorial: Build a Document Q&A System Step by Step",
    "description": "Build a complete RAG pipeline with LangChain — document loading, text splitting, vector store indexing, retrieval chains, and conversational Q&A with memory.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "langchain-tutorial-complete",
    "title": "LangChain Complete Tutorial: Chains, Agents, Tools, and Memory",
    "description": "Master LangChain from scratch — LLM wrappers, prompt templates, chains, LCEL, agents with tools, memory, and building production applications.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "llm-inference-and-serving",
    "title": "LLM Inference and Serving: vLLM, Ollama, and Production Optimization",
    "description": "Guide to LLM inference optimization — KV cache, continuous batching, quantization, vLLM serving, Ollama local deployment, and benchmarking throughput and latency.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "machine-learning-basics-for-developers",
    "title": "Machine Learning Basics for Developers: A Practical Introduction",
    "description": "A developer-first introduction to machine learning — core concepts, types of ML, hands-on Python workflow, and how to go from data to a working model.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "model-evaluation-and-metrics",
    "title": "Model Evaluation and Metrics: How to Measure ML Model Performance",
    "description": "Complete guide to ML evaluation metrics — accuracy, precision, recall, F1, AUC-ROC, RMSE, confusion matrices, learning curves, and cross-validation strategies.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "open-source-llms-guide",
    "title": "Open Source LLMs Guide: Llama, Mistral, Gemma, and How to Run Them Locally",
    "description": "Compare the top open source LLMs — Llama 3, Mistral, Gemma, Phi — and learn how to run them locally with Ollama, llama.cpp, and Hugging Face Transformers.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "openai-api-complete-guide",
    "title": "OpenAI API Complete Guide: Chat, Embeddings, Functions, and Streaming",
    "description": "Master the OpenAI API — chat completions, function calling, embeddings, streaming responses, error handling, cost optimization, and building production-ready integrations.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "python-for-machine-learning",
    "title": "Python for Machine Learning: NumPy, Pandas, and Scikit-learn Essentials",
    "description": "The Python toolkit every ML engineer needs — NumPy arrays, pandas DataFrames, data visualization with matplotlib, and scikit-learn's core API.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "rag-system-architecture",
    "title": "RAG System Architecture: Design Patterns for Production Retrieval-Augmented Generation",
    "description": "Architecture guide for production RAG systems — naive RAG vs advanced RAG, indexing pipelines, hybrid search, reranking, guardrails, and performance optimization.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "supervised-learning-guide",
    "title": "Supervised Learning Guide: Algorithms, Workflows, and Best Practices",
    "description": "Deep dive into supervised learning — regression and classification algorithms, evaluation metrics, cross-validation, and how to pick the right model for your problem.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 7
  },
  {
    "slug": "tool-use-and-function-calling",
    "title": "Tool Use and Function Calling in LLMs: Practical Patterns and Best Practices",
    "description": "Complete guide to LLM function calling — defining tools, parallel tool calls, error handling, designing reliable tool schemas, and building agentic pipelines.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ai-roadmap-for-developers",
    "title": "AI Roadmap for Developers 2026: The Complete Learning Path",
    "description": "The definitive AI learning roadmap for software developers in 2026. Follow 7 phases from AI foundations to building and shipping real AI projects — with free resources and milestone projects.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 7
  },
  {
    "slug": "how-to-become-ai-engineer",
    "title": "How to Become an AI Engineer in 2026 (From Any Background)",
    "description": "A practical guide to becoming an AI engineer in 2026. Learn what skills you need, how long it takes, what to build, and how to land your first AI engineering role — from any starting point.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 5
  },
  {
    "slug": "llm-quantization",
    "title": "LLM Quantization: Run 70B Models on Consumer GPUs with GGUF & GPTQ",
    "description": "Master LLM quantization — INT4, INT8, GGUF, and GPTQ formats — to run 70B models on consumer GPUs with minimal quality loss, with Python examples.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 7
  },
  {
    "slug": "machine-learning-roadmap",
    "title": "Machine Learning Roadmap 2026: From Beginner to Job-Ready",
    "description": "The complete machine learning roadmap for 2026. Learn Python, math fundamentals, classical ML, deep learning, LLMs, and MLOps — with free resources and project milestones at each stage.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 6
  },
  {
    "slug": "rag-tutorial-step-by-step",
    "title": "RAG Tutorial 2026: Build a Retrieval-Augmented Generation Pipeline from Scratch",
    "description": "Step-by-step RAG tutorial for developers in 2026. Build a complete Retrieval-Augmented Generation pipeline — document loading, chunking, vector embeddings, semantic search, and LLM generation with LangChain and ChromaDB.",
    "date": "2026-03-09",
    "date_display": "March 9, 2026",
    "mins": 5
  },
  {
    "slug": "llm-hardware-guide",
    "title": "LLM Hardware Guide: GPU Requirements for Running and Training LLMs (2026)",
    "description": "GPU and hardware requirements for running and training LLMs — VRAM by model size, GPU tier comparisons, Apple Silicon, quantization trade-offs, and cloud vs local.",
    "date": "2026-03-07",
    "date_display": "March 7, 2026",
    "mins": 11
  },
  {
    "slug": "llm-function-calling",
    "title": "LLM Function Calling: Build Tool-Using AI Apps with OpenAI & Claude (2026)",
    "description": "Learn LLM function calling with OpenAI and Claude — define tool schemas, handle tool calls, chain results, and build real tool-using AI applications in Python.",
    "date": "2026-03-06",
    "date_display": "March 6, 2026",
    "mins": 10
  },
  {
    "slug": "llm-evaluation",
    "title": "LLM Evaluation: How to Test and Score Language Model Quality (2026)",
    "description": "Systematic methods for evaluating LLM quality — perplexity, BLEU, ROUGE, LLM-as-judge, task-specific evals, and benchmark regression testing with Python code.",
    "date": "2026-03-04",
    "date_display": "March 4, 2026",
    "mins": 9
  },
  {
    "slug": "llm-benchmarks",
    "title": "LLM Benchmarks Explained: MMLU, HumanEval, GPQA & What They Mean (2026)",
    "description": "Understand the key LLM benchmarks developers use to compare models — MMLU, HumanEval, GPQA, MATH — what they measure and what they miss in production.",
    "date": "2026-03-02",
    "date_display": "March 2, 2026",
    "mins": 9
  },
  {
    "slug": "llm-api-guide",
    "title": "LLM API Guide: Choosing and Using OpenAI, Anthropic & Gemini APIs (2026)",
    "description": "Compare and use the major LLM APIs in Python — OpenAI, Anthropic Claude, and Google Gemini — with auth, streaming, error handling, and cost management.",
    "date": "2026-02-28",
    "date_display": "February 28, 2026",
    "mins": 10
  },
  {
    "slug": "llm-api-errors",
    "title": "LLM API Error Handling: Retries, Rate Limits & Fallbacks in Python (2026)",
    "description": "Learn how to handle LLM API errors robustly in Python — retries, exponential backoff, rate limits, and multi-provider fallbacks for production apps.",
    "date": "2026-02-25",
    "date_display": "February 25, 2026",
    "mins": 11
  },
  {
    "slug": "llm-api-cost-optimization",
    "title": "LLM API Cost Optimization: Cut Your OpenAI Bills by 60–80% (2026)",
    "description": "Cut your LLM API costs by 60–80% using prompt caching, model routing, response caching, and batch APIs. Includes real cost math and Python optimization code.",
    "date": "2026-02-23",
    "date_display": "February 23, 2026",
    "mins": 12
  },
  {
    "slug": "instruction-tuning",
    "title": "Instruction Tuning: How to Train LLMs to Follow Instructions (2026)",
    "description": "Learn how instruction tuning trains LLMs to follow natural language instructions. Covers Alpaca format, chat templates, multi-turn data, and TRL SFTTrainer with Python.",
    "date": "2026-02-21",
    "date_display": "February 21, 2026",
    "mins": 10
  },
  {
    "slug": "huggingface-training",
    "title": "Fine-Tuning LLMs with HuggingFace Transformers: Complete Guide (2026)",
    "description": "Complete guide to fine-tuning LLMs with HuggingFace Transformers. Covers Trainer, TRL SFTTrainer, PEFT, and Accelerate for multi-GPU training with Python code.",
    "date": "2026-02-18",
    "date_display": "February 18, 2026",
    "mins": 9
  },
  {
    "slug": "gguf-models",
    "title": "GGUF Models Explained: Run Quantized LLMs Locally with Ollama & llama.cpp",
    "description": "Learn what GGUF models are and how to run quantized LLMs locally with Ollama and llama.cpp. Covers Q4_K_M vs Q8_0 quant levels with Python loading examples.",
    "date": "2026-02-16",
    "date_display": "February 16, 2026",
    "mins": 8
  },
  {
    "slug": "gemini-api-tutorial",
    "title": "Google Gemini API Tutorial: Build AI Apps with Python (2026)",
    "description": "Build AI apps with the Google Gemini API in Python. Covers setup, generateContent, streaming, multimodal inputs, and function calling with complete code examples.",
    "date": "2026-02-14",
    "date_display": "February 14, 2026",
    "mins": 9
  },
  {
    "slug": "full-vs-lora",
    "title": "Full Fine-Tuning vs LoRA: When to Use Each for LLM Training (2026)",
    "description": "Compare full fine-tuning vs LoRA for LLMs with real compute cost, memory, and quality numbers. A practical decision guide with Python training code examples.",
    "date": "2026-02-11",
    "date_display": "February 11, 2026",
    "mins": 8
  },
  {
    "slug": "finetuning-datasets",
    "title": "How to Build Fine-Tuning Datasets for LLMs: Format, Quality & Scale",
    "description": "Learn how to build high-quality fine-tuning datasets for LLMs. Covers Alpaca format, ShareGPT, deduplication, quality filtering, and synthetic data generation.",
    "date": "2026-02-09",
    "date_display": "February 9, 2026",
    "mins": 10
  },
  {
    "slug": "fine-tune-open-source-llm",
    "title": "Fine-Tune Open Source LLMs: Llama 3, Mistral & Phi-4 Guide (2026)",
    "description": "Step-by-step guide to fine-tuning Llama 3, Mistral, and Phi-4 using LoRA and QLoRA. Covers dataset prep, training, adapter merging, and serving with Ollama.",
    "date": "2026-02-07",
    "date_display": "February 7, 2026",
    "mins": 9
  },
  {
    "slug": "distributed-llm-training",
    "title": "Distributed LLM Training: Data Parallelism, Model Sharding & ZeRO (2026)",
    "description": "Learn distributed LLM training strategies including data parallelism, model sharding, and DeepSpeed ZeRO. Includes HuggingFace Accelerate and FSDP config examples.",
    "date": "2026-02-04",
    "date_display": "February 4, 2026",
    "mins": 11
  },
  {
    "slug": "autonomous-agents",
    "title": "Autonomous AI Agents: How They Work and How to Build One (2026)",
    "description": "Learn how autonomous AI agents work and how to build one in Python. Covers loop architecture, error recovery, self-correction, and production safety considerations.",
    "date": "2026-02-02",
    "date_display": "February 2, 2026",
    "mins": 10
  },
  {
    "slug": "api-vs-local-llm",
    "title": "LLM API vs Running Locally: Cost, Latency & Privacy Trade-offs (2026)",
    "description": "Compare LLM API vs local deployment on cost, latency, privacy, and capability. Real cost calculations for OpenAI API vs Ollama with a Python decision framework.",
    "date": "2026-01-31",
    "date_display": "January 31, 2026",
    "mins": 10
  },
  {
    "slug": "anthropic-api-tutorial",
    "title": "Anthropic Claude API Tutorial: Complete Developer Guide (2026)",
    "description": "Complete guide to the Anthropic Claude API in Python. Covers Messages API, streaming, tool use, vision, and system prompts with runnable code examples.",
    "date": "2026-01-28",
    "date_display": "January 28, 2026",
    "mins": 10
  },
  {
    "slug": "ai-agents-tutorial",
    "title": "Build Your First AI Agent in Python: Step-by-Step Tutorial (2026)",
    "description": "Step-by-step Python tutorial to build your first AI agent from scratch using LangChain. Covers ReAct loop, tool calling, and memory — with full runnable code.",
    "date": "2026-01-26",
    "date_display": "January 26, 2026",
    "mins": 10
  },
  {
    "slug": "ai-agent-architecture",
    "title": "AI Agent Architecture: Design Patterns for Production LLM Agents (2026)",
    "description": "Explore AI agent architecture patterns for production LLM systems. Learn perception, memory, planning, and tool components with Python code and design diagrams.",
    "date": "2026-01-24",
    "date_display": "January 24, 2026",
    "mins": 11
  },
  {
    "slug": "agent-tools",
    "title": "AI Agent Tool Use: How to Give LLMs Access to APIs, Code & Search (2026)",
    "description": "Learn how to give LLM agents access to APIs, code execution, and web search. Includes Python examples for building custom tools with LangChain and OpenAI functions.",
    "date": "2026-01-21",
    "date_display": "January 21, 2026",
    "mins": 11
  },
  {
    "slug": "agent-planning",
    "title": "LLM Agent Planning: ReAct, Tree of Thought & Hierarchical Planning (2026)",
    "description": "Master LLM agent planning strategies including ReAct, Tree of Thought, and hierarchical planning. Includes runnable Python code for each planning pattern.",
    "date": "2026-01-19",
    "date_display": "January 19, 2026",
    "mins": 10
  },
  {
    "slug": "agent-memory",
    "title": "Agent Memory Systems: Short-Term, Long-Term & Episodic Memory for LLM Agents",
    "description": "Understand short-term, long-term, and episodic memory in LLM agents. Learn how to implement each memory type in Python with LangChain and vector stores.",
    "date": "2026-01-17",
    "date_display": "January 17, 2026",
    "mins": 10
  },
  {
    "slug": "agent-framework-comparison",
    "title": "LangGraph vs AutoGen vs CrewAI: AI Agent Framework Comparison (2026)",
    "description": "Compare LangGraph, AutoGen, and CrewAI agent frameworks on control, ease of use, multi-agent support, and production readiness with code examples.",
    "date": "2026-01-14",
    "date_display": "January 14, 2026",
    "mins": 9
  },
  {
    "slug": "agent-evaluation",
    "title": "How to Evaluate AI Agents: Metrics, Frameworks & Testing Patterns (2026)",
    "description": "Learn how to evaluate LLM agents using task success rate, trajectory quality, and tool use accuracy. Includes Python evaluation harness and LangSmith tracing.",
    "date": "2026-01-12",
    "date_display": "January 12, 2026",
    "mins": 10
  }
];
const ROADMAP_GUIDES = [
  {
    "slug": "ai-agent-evaluation",
    "title": "AI Agent Evaluation: Testing, Benchmarking, and Safety for Agentic Systems",
    "description": "Learn how to rigorously evaluate AI agents — building test suites, measuring task completion rates, detecting failures, red-teaming, and implementing safety guardrails for production deployments.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ai-foundations-for-developers",
    "title": "AI Foundations for Developers: Core Concepts You Must Know",
    "description": "A developer-focused introduction to AI fundamentals: what AI, ML, and deep learning actually are, how they differ, and the mental models you need before writing your first AI application.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "building-ai-agents-guide",
    "title": "Building AI Agents: ReAct, Tool Use, and Agentic Workflows",
    "description": "A practical guide to building AI agents that can reason and act — covering the ReAct pattern, tool definition, agent loops, memory strategies, and multi-step task execution with OpenAI function calling.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "deep-learning-fundamentals",
    "title": "Deep Learning Fundamentals: CNNs, RNNs, and the Road to Transformers",
    "description": "Understand the deep learning architectures that shaped modern AI — convolutional networks for images, recurrent networks for sequences, and how their limitations led to the transformer revolution.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "how-llms-work",
    "title": "How LLMs Work: From Pretraining to ChatGPT — A Developer's Guide",
    "description": "A technical deep dive into how large language models actually work — tokenization, pretraining, RLHF, inference, and the architectural decisions that define modern LLMs like GPT-4 and Claude.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 6
  },
  {
    "slug": "linear-algebra-for-ai",
    "title": "Linear Algebra for AI Developers: The Concepts That Actually Matter",
    "description": "A practical guide to the linear algebra used in AI and machine learning — vectors, matrices, dot products, and matrix multiplication explained with Python code and real AI use cases.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "ml-project-workflow",
    "title": "ML Project Workflow: End-to-End Machine Learning in Practice",
    "description": "A practical guide to the full machine learning project lifecycle — problem framing, data collection, feature engineering, model selection, evaluation, and deployment — with Python code at every step.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "neural-networks-from-scratch",
    "title": "Neural Networks from Scratch: Build One in Pure Python",
    "description": "Build a neural network from scratch using only NumPy to understand how forward passes, backpropagation, and gradient descent actually work. No frameworks, just the math made concrete.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "production-rag-best-practices",
    "title": "Production RAG Best Practices: Chunking, Reranking, and Evaluation",
    "description": "Go beyond basic RAG with advanced techniques: recursive chunking strategies, metadata filtering, reranking retrieved documents, evaluating RAG pipelines, and building production-ready retrieval systems.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "python-for-ai-complete-guide",
    "title": "Python for AI Developers: Complete Setup and Essential Libraries",
    "description": "Set up a production-ready Python AI development environment. Covers virtual environments, essential libraries (NumPy, pandas, OpenAI SDK), Jupyter notebooks, and common patterns used in AI projects.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "pytorch-for-ai-developers",
    "title": "PyTorch for AI Developers: Practical Guide from Tensors to Training",
    "description": "A hands-on PyTorch guide covering tensors, autograd, model building with nn.Module, training loops, GPU acceleration, and loading pre-trained models from HuggingFace.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  },
  {
    "slug": "semantic-search-explained",
    "title": "Semantic Search Explained: How Embeddings Enable Meaning-Based Search",
    "description": "Understand how semantic search works — from text embeddings and vector spaces to HNSW indexes and approximate nearest neighbor search. Build a production-quality semantic search engine in Python.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "statistics-for-machine-learning",
    "title": "Statistics for Machine Learning: Practical Concepts for Developers",
    "description": "The statistical concepts that actually matter for ML practitioners — probability distributions, Bayes' theorem, hypothesis testing, and how to interpret model evaluation metrics correctly.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 5
  },
  {
    "slug": "working-with-local-llms",
    "title": "Working with Local LLMs: Run AI Models Privately with Ollama and llama.cpp",
    "description": "Run powerful LLMs completely offline on your own hardware. Set up Ollama, run Llama 3, Mistral, and Code Llama locally, build Python integrations, and understand when to use local vs API models.",
    "date": "2026-03-10",
    "date_display": "March 10, 2026",
    "mins": 4
  }
];
const PROJECT_LIST = [
  {
    "slug": "ai-chatbot-python",
    "title": "Build an AI Chatbot in Python: Complete Beginner Project",
    "description": "Build a multi-turn AI chatbot in Python using the OpenAI API. Includes conversation memory, streaming, a CLI interface, and a simple Gradio web UI.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Gradio"
  },
  {
    "slug": "ai-code-explainer",
    "title": "Build an AI Code Explainer: Understand Any Code Instantly",
    "description": "Build a tool that explains code in plain English, identifies bugs, suggests improvements, and generates documentation — for any programming language.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Click"
  },
  {
    "slug": "ai-email-writer",
    "title": "Build an AI Email Writer: Draft Professional Emails in Seconds",
    "description": "Build an AI tool that drafts professional emails from bullet points or brief descriptions. Supports multiple tones, templates, and a Streamlit web UI.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, Streamlit"
  },
  {
    "slug": "ai-quiz-generator",
    "title": "Build an AI Quiz Generator from Any Text or Document",
    "description": "Build an AI tool that generates multiple-choice quizzes from any text, PDF, or topic. Export to JSON, run interactively, and track scores.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, JSON"
  },
  {
    "slug": "ai-resume-analyzer",
    "title": "Build an AI Resume Analyzer: Score, Critique, and Improve Resumes",
    "description": "Build a tool that analyzes resumes against job descriptions, scores fit, identifies gaps, and suggests specific improvements using GPT-4o-mini.",
    "level": "Beginner",
    "time": "3–4 hours",
    "stack": "Python, OpenAI API, pypdf, Streamlit"
  },
  {
    "slug": "build-chatgpt-clone",
    "title": "Build a ChatGPT Clone from Scratch: Full-Stack AI Chat App",
    "description": "Build a full-stack conversational AI app with streaming responses, persistent conversation history, and a React chat UI — using FastAPI and the OpenAI API.",
    "level": "Beginner",
    "time": "3–4 hours",
    "stack": "Python, FastAPI, React, OpenAI API"
  },
  {
    "slug": "document-summarizer",
    "title": "Build an AI Document Summarizer: PDF, Text, and URL Summarization",
    "description": "Build an AI-powered document summarizer that handles PDFs, plain text, and web URLs. Supports map-reduce summarization for long documents and outputs key bullet points.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, PyPDF2, BeautifulSoup"
  },
  {
    "slug": "sentiment-analyzer",
    "title": "Build an AI Sentiment Analyzer: Classify Text Sentiment and Emotions",
    "description": "Build a sentiment analysis tool using GPT-4o-mini that classifies text as positive, negative, or neutral, detects emotions, and processes batches of reviews or tweets.",
    "level": "Beginner",
    "time": "2–3 hours",
    "stack": "Python, OpenAI API, pandas"
  },
  {
    "slug": "ai-content-moderator",
    "title": "Build an AI Content Moderator: Classify and Filter Harmful Content",
    "description": "Build a content moderation system that classifies text and images for toxicity, hate speech, spam, and policy violations. Includes a review queue and confidence thresholds.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API (Moderation + GPT), FastAPI, SQLite"
  },
  {
    "slug": "ai-data-analyst",
    "title": "Build an AI Data Analyst: Chat with Your CSV Data",
    "description": "Build a natural language data analysis tool that lets you ask questions about CSV datasets. Generates and executes Python pandas code, produces charts, and explains insights automatically.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API, pandas, matplotlib, Streamlit"
  },
  {
    "slug": "ai-meeting-summarizer",
    "title": "Build an AI Meeting Summarizer: Transcribe and Summarize Meetings Automatically",
    "description": "Build a tool that transcribes audio recordings with Whisper, summarizes with GPT-4o-mini, extracts action items, decisions, and attendee contributions into a structured meeting report.",
    "level": "Intermediate",
    "time": "3–5 hours",
    "stack": "Python, OpenAI API (Whisper + GPT), Streamlit"
  },
  {
    "slug": "ai-research-assistant",
    "title": "Build an AI Research Assistant: Summarize Papers and Extract Insights",
    "description": "Build an AI tool that reads academic papers and web pages, extracts key findings, compares multiple sources, and generates research summaries with citations.",
    "level": "Intermediate",
    "time": "4–5 hours",
    "stack": "Python, OpenAI API, requests, BeautifulSoup, Streamlit"
  },
  {
    "slug": "ai-support-bot",
    "title": "Build an AI Customer Support Bot with Knowledge Base",
    "description": "Build a production-ready customer support chatbot that answers questions from your documentation, escalates complex issues, maintains conversation history, and handles tone appropriately.",
    "level": "Intermediate",
    "time": "5–6 hours",
    "stack": "Python, OpenAI API, ChromaDB, FastAPI, Streamlit"
  },
  {
    "slug": "rag-document-assistant",
    "title": "Build a RAG Document Assistant: Chat with Your Documents",
    "description": "Build a Retrieval-Augmented Generation system that lets you upload documents and ask questions. Uses embeddings, vector search, and GPT-4o-mini for accurate, grounded answers.",
    "level": "Intermediate",
    "time": "4–6 hours",
    "stack": "Python, OpenAI API, ChromaDB, Streamlit"
  },
  {
    "slug": "voice-ai-assistant",
    "title": "Build a Voice AI Assistant: Speech-to-Speech Conversational AI",
    "description": "Build a voice-enabled AI assistant using Whisper for speech recognition, GPT-4o-mini for responses, and TTS for natural voice output. Supports wake word detection and conversation memory.",
    "level": "Intermediate",
    "time": "4–6 hours",
    "stack": "Python, OpenAI API (Whisper + GPT + TTS), sounddevice, pygame"
  },
  {
    "slug": "ai-code-review-assistant",
    "title": "Build an AI Code Review Assistant: Automated PR Reviews",
    "description": "Build a tool that reviews Git diffs and pull requests, identifies bugs, security issues, style violations, and suggests improvements — integrated with GitHub Actions.",
    "level": "Advanced",
    "time": "6–8 hours",
    "stack": "Python, OpenAI API, GitHub API, FastAPI"
  },
  {
    "slug": "ai-personal-knowledge-base",
    "title": "Build an AI Personal Knowledge Base: Your Second Brain with AI",
    "description": "Build a personal knowledge management system that ingests notes, web clips, and PDFs, auto-links related content, and lets you have conversations with your accumulated knowledge.",
    "level": "Advanced",
    "time": "8–12 hours",
    "stack": "Python, OpenAI API, ChromaDB, SQLite, Streamlit"
  },
  {
    "slug": "ai-sales-agent",
    "title": "Build an AI Sales Agent: Automated Lead Qualification and Outreach",
    "description": "Build an AI sales agent that qualifies leads from a CRM, personalizes outreach emails based on company research, tracks responses, and generates pipeline reports.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, SQLite, FastAPI, requests"
  },
  {
    "slug": "ai-security-analyzer",
    "title": "Build an AI Security Analyzer: Automated Vulnerability Detection",
    "description": "Build a static analysis tool that scans codebases for security vulnerabilities using GPT-4o-mini, detecting OWASP Top 10 issues, secrets in code, and insecure patterns with severity scoring.",
    "level": "Advanced",
    "time": "6–8 hours",
    "stack": "Python, OpenAI API, GitPython, Click"
  },
  {
    "slug": "ai-study-planner",
    "title": "Build an AI Study Planner: Personalized Learning Schedules with Spaced Repetition",
    "description": "Build an AI study planner that creates personalized schedules, generates practice questions using spaced repetition, tracks progress, and adapts the plan based on performance.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, SQLite, Streamlit, schedule"
  },
  {
    "slug": "multi-agent-research-system",
    "title": "Build a Multi-Agent Research System: Parallel AI Agents for Deep Research",
    "description": "Build a multi-agent system where a Planner agent breaks research questions into sub-tasks, Researcher agents gather information in parallel, and a Synthesizer agent produces a comprehensive report.",
    "level": "Advanced",
    "time": "8–10 hours",
    "stack": "Python, OpenAI API, asyncio, Tavily Search API, Streamlit"
  }
];
const PATH_LIST = [
  {
    "slug": "ai-engineer",
    "title": "AI Engineer Learning Path",
    "description": "A complete roadmap to becoming an AI Engineer — the generalist role that designs, builds, and ships AI-powered applications and systems in production.",
    "timeline": "6–12 months",
    "salary": "$130k–$220k",
    "demand": "Very High"
  },
  {
    "slug": "ai-product-engineer",
    "title": "AI Product Engineer Learning Path",
    "description": "Bridge product thinking and AI engineering — the AI Product Engineer path covers building user-facing AI features, designing great AI UX, and shipping AI products end to end.",
    "timeline": "6–10 months",
    "salary": "$130k–$210k",
    "demand": "High"
  },
  {
    "slug": "ai-research-engineer",
    "title": "AI Research Engineer Learning Path",
    "description": "Go deep on the science of AI — the AI Research Engineer path covers mathematical foundations, novel architectures, paper implementation, and contributing to the frontier of AI research.",
    "timeline": "12–24 months",
    "salary": "$160k–$350k",
    "demand": "Moderate"
  },
  {
    "slug": "llm-engineer",
    "title": "LLM Engineer Learning Path",
    "description": "Master large language models from the inside out — the LLM Engineer path covers transformer architecture, fine-tuning, inference optimization, and deploying custom models at scale.",
    "timeline": "9–15 months",
    "salary": "$150k–$260k",
    "demand": "Very High"
  },
  {
    "slug": "ml-engineer",
    "title": "ML Engineer Learning Path",
    "description": "From data to deployed models — the ML Engineer path covers the full machine learning lifecycle: data pipelines, model training, evaluation, MLOps, and production serving.",
    "timeline": "8–14 months",
    "salary": "$140k–$230k",
    "demand": "High"
  }
];
